<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_batch_queue.queue.database_job_execution_queue' shared service.

return $this->services['akeneo_batch_queue.queue.database_job_execution_queue'] = new \Akeneo\Tool\Bundle\BatchQueueBundle\Queue\DatabaseJobExecutionQueue(${($_ = isset($this->services['akeneo_batch_queue.queue.job_execution_message_repository']) ? $this->services['akeneo_batch_queue.queue.job_execution_message_repository'] : $this->load(__DIR__.'/getAkeneoBatchQueue_Queue_JobExecutionMessageRepositoryService.php')) && false ?: '_'});
