<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_channel.job.job_parameters.constraint_collection_provider.simple_xlsx_export' shared service.

return $this->services['akeneo_channel.job.job_parameters.constraint_collection_provider.simple_xlsx_export'] = new \Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxExport(array(0 => 'xlsx_channel_export', 1 => 'xlsx_locale_export', 2 => 'xlsx_currency_export'));
