<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo.pim.enrichment.product.grid.query.add_additional_product_model_properties' shared service.

return $this->services['akeneo.pim.enrichment.product.grid.query.add_additional_product_model_properties'] = new \Akeneo\Pim\Enrichment\Component\Product\Grid\Query\AddAdditionalProductModelPropertiesRegistry(new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
