<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_file_storage.file_storage.formater.bytes' shared service.

return $this->services['akeneo_file_storage.file_storage.formater.bytes'] = new \Akeneo\Tool\Component\FileStorage\Formater\BytesFormater();
