<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_elasticsearch.client_builder' shared service.

return $this->services['akeneo_elasticsearch.client_builder'] = new \Elasticsearch\ClientBuilder();
