<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_measure.controller.rest.measures' shared service.

return $this->services['akeneo_measure.controller.rest.measures'] = new \Akeneo\Tool\Bundle\MeasureBundle\Controller\MeasuresController($this->parameters['akeneo_measure.measures_config']);
