<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_batch.logger_subscriber' shared service.

return $this->services['akeneo_batch.logger_subscriber'] = new \Akeneo\Tool\Bundle\BatchBundle\EventListener\LoggerSubscriber(${($_ = isset($this->services['monolog.logger.batch']) ? $this->services['monolog.logger.batch'] : $this->load(__DIR__.'/getMonolog_Logger_BatchService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
