<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_xlsx_export' shared service.

return $this->services['akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_xlsx_export'] = new \Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxExport(array(0 => 'xlsx_attribute_export', 1 => 'xlsx_family_export', 2 => 'xlsx_family_variant_export', 3 => 'xlsx_association_type_export', 4 => 'xlsx_attribute_option_export', 5 => 'xlsx_attribute_group_export', 6 => 'xlsx_group_type_export'));
