<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.dbal.default.wrapped_connection' shared service.

return $this->services['doctrine.dbal.default.wrapped_connection'] = ${($_ = isset($this->services['doctrine.dbal.session_connection']) ? $this->services['doctrine.dbal.session_connection'] : $this->load(__DIR__.'/getDoctrine_Dbal_SessionConnectionService.php')) && false ?: '_'}->getWrappedConnection();
