<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_datagrid.extension.pager.dummy_pager' shared service.

return $this->services['oro_datagrid.extension.pager.dummy_pager'] = new \Oro\Bundle\DataGridBundle\Extension\Pager\DummyPager();
