<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.controller.currency' shared service.

return $this->services['pim_enrich.controller.currency'] = new \Akeneo\Channel\Bundle\Controller\UI\CurrencyController(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.saver.currency']) ? $this->services['pim_catalog.saver.currency'] : $this->load(__DIR__.'/getPimCatalog_Saver_CurrencyService.php')) && false ?: '_'});
