<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.version_provider' shared service.

return $this->services['pim_catalog.version_provider'] = new \Akeneo\Platform\VersionProvider('Akeneo\\Platform\\CommunityVersion');
