<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.attribute_group' shared service.

return $this->services['pim_catalog.updater.attribute_group'] = new \Akeneo\Pim\Structure\Component\Updater\AttributeGroupUpdater(${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_AttributeService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.attribute_group']) ? $this->services['pim_catalog.repository.attribute_group'] : $this->load(__DIR__.'/getPimCatalog_Repository_AttributeGroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_structure.updater.translatable']) ? $this->services['pim_structure.updater.translatable'] : $this->services['pim_structure.updater.translatable'] = new \Akeneo\Tool\Component\Localization\TranslatableUpdater()) && false ?: '_'});
