<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_ui.form.transformer.ajax_entity.factory' shared service.

return $this->services['pim_ui.form.transformer.ajax_entity.factory'] = new \Akeneo\Platform\Bundle\UIBundle\Form\Transformer\AjaxEntityTransformerFactory(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'Akeneo\\Platform\\Bundle\\UIBundle\\Form\\Transformer\\AjaxEntityTransformer');
