<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.incomplete_values' shared service.

return $this->services['pim_enrich.normalizer.incomplete_values'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\IncompleteValuesNormalizer(${($_ = isset($this->services['pim_catalog.entity_with_family.required_value_collection_factory']) ? $this->services['pim_catalog.entity_with_family.required_value_collection_factory'] : $this->services['pim_catalog.entity_with_family.required_value_collection_factory'] = new \Akeneo\Pim\Enrichment\Component\Product\EntityWithFamily\RequiredValueCollectionFactory()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.entity_with_family.incomplete_value_collection_factory']) ? $this->services['pim_catalog.entity_with_family.incomplete_value_collection_factory'] : $this->load(__DIR__.'/getPimCatalog_EntityWithFamily_IncompleteValueCollectionFactoryService.php')) && false ?: '_'});
