<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.view_element.user.tab.password' shared service.

$this->services['pim_user.view_element.user.tab.password'] = $instance = new \Akeneo\Platform\Bundle\UIBundle\ViewElement\BaseViewElement('pim_user.user.tabs.password', 'PimUserBundle:User:Tab/password.html.twig');

$instance->addVisibilityChecker(${($_ = isset($this->services['pim_enrich.view_element.visibility_checker.non_empty_property']) ? $this->services['pim_enrich.view_element.visibility_checker.non_empty_property'] : $this->services['pim_enrich.view_element.visibility_checker.non_empty_property'] = new \Akeneo\Platform\Bundle\UIBundle\ViewElement\Checker\NonEmptyPropertyVisibilityChecker()) && false ?: '_'}, array('property' => '[form].children[change_password]'));

return $instance;
