<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.entity_with_family.incomplete_value_collection_factory' shared service.

return $this->services['pim_catalog.entity_with_family.incomplete_value_collection_factory'] = new \Akeneo\Pim\Enrichment\Component\Product\EntityWithFamily\IncompleteValueCollectionFactory(${($_ = isset($this->services['pim_catalog.completeness.checker']) ? $this->services['pim_catalog.completeness.checker'] : $this->load(__DIR__.'/getPimCatalog_Completeness_CheckerService.php')) && false ?: '_'});
