<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.pagination.parameter_validator' shared service.

return $this->services['pim_api.pagination.parameter_validator'] = new \Akeneo\Tool\Component\Api\Pagination\ParameterValidator($this->parameters['pim_api.configuration']);
