<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.saver.product' shared service.

return $this->services['pim_catalog.saver.product'] = new \Akeneo\Pim\Enrichment\Bundle\Doctrine\Common\Saver\ProductSaver(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.manager.completeness']) ? $this->services['pim_catalog.manager.completeness'] : $this->load(__DIR__.'/getPimCatalog_Manager_CompletenessService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.synchronizer.product_unique_data']) ? $this->services['pim_catalog.synchronizer.product_unique_data'] : $this->load(__DIR__.'/getPimCatalog_Synchronizer_ProductUniqueDataService.php')) && false ?: '_'});
