<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.event_listener.configure_sorters_listener' shared service.

return $this->services['pim_datagrid.event_listener.configure_sorters_listener'] = new \Oro\Bundle\PimDataGridBundle\EventListener\ConfigureSortersListener();
