<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_ui.twig.ui_extension' shared service.

return $this->services['pim_ui.twig.ui_extension'] = new \Akeneo\Platform\Bundle\UIBundle\Twig\UiExtension($this->parameters['pim_ui.placeholders'], 'block-wrap');
