<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.product_query_builder.filter.dummy' shared service.

return $this->services['pim_enrich.product_query_builder.filter.dummy'] = new \Akeneo\Pim\Enrichment\Bundle\ProductQueryBuilder\Filter\DummyFilter(array(), array(0 => 'enabled', 1 => 'completeness'), array(0 => 'ALL'));
