<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.attributetype.boolean' shared service.

return $this->services['pim_catalog.attributetype.boolean'] = new \Akeneo\Pim\Structure\Component\AttributeType\BooleanType('boolean');
