<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_ui.form.type.date' shared service.

return $this->services['pim_ui.form.type.date'] = new \Akeneo\Platform\Bundle\UIBundle\Form\Type\DateType(${($_ = isset($this->services['pim_enrich.resolver.locale']) ? $this->services['pim_enrich.resolver.locale'] : $this->load(__DIR__.'/getPimEnrich_Resolver_LocaleService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.factory.date']) ? $this->services['pim_catalog.localization.factory.date'] : $this->load(__DIR__.'/getPimCatalog_Localization_Factory_DateService.php')) && false ?: '_'});
