<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.adapter_resolver' shared service.

$this->services['pim_datagrid.datasource.adapter_resolver'] = $instance = new \Oro\Bundle\PimDataGridBundle\Datasource\DatasourceAdapterResolver('Oro\\Bundle\\PimFilterBundle\\Datasource\\Orm\\OrmFilterDatasourceAdapter', 'Oro\\Bundle\\PimFilterBundle\\Datasource\\Orm\\OrmFilterProductDatasourceAdapter');

$instance->addProductDatasource('pim_datasource_product');
$instance->addProductDatasource('pim_datasource_associated_product');
$instance->addProductDatasource('pim_datasource_associated_product_model');
$instance->addProductDatasource('pim_datasource_group_product');
$instance->addProductDatasource('pimee_datasource_published_product');
$instance->addProductDatasource('pimee_datasource_proposal_product');

return $instance;
