<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.event_listener.archivist' shared service.

$this->services['pim_connector.event_listener.archivist'] = $instance = new \Akeneo\Tool\Bundle\ConnectorBundle\EventListener\JobExecutionArchivist();

$instance->registerArchiver(${($_ = isset($this->services['pim_connector.archiver.file_reader_archiver']) ? $this->services['pim_connector.archiver.file_reader_archiver'] : $this->load(__DIR__.'/getPimConnector_Archiver_FileReaderArchiverService.php')) && false ?: '_'});
$instance->registerArchiver(${($_ = isset($this->services['pim_connector.archiver.file_writer_archiver']) ? $this->services['pim_connector.archiver.file_writer_archiver'] : $this->load(__DIR__.'/getPimConnector_Archiver_FileWriterArchiverService.php')) && false ?: '_'});
$instance->registerArchiver(${($_ = isset($this->services['pim_connector.archiver.archivable_file_writer_archiver']) ? $this->services['pim_connector.archiver.archivable_file_writer_archiver'] : $this->load(__DIR__.'/getPimConnector_Archiver_ArchivableFileWriterArchiverService.php')) && false ?: '_'});
$instance->registerArchiver(${($_ = isset($this->services['pim_connector.archiver.invalid_item_csv_writer']) ? $this->services['pim_connector.archiver.invalid_item_csv_writer'] : $this->load(__DIR__.'/getPimConnector_Archiver_InvalidItemCsvWriterService.php')) && false ?: '_'});
$instance->registerArchiver(${($_ = isset($this->services['pim_connector.archiver.invalid_item_xlsx_writer']) ? $this->services['pim_connector.archiver.invalid_item_xlsx_writer'] : $this->load(__DIR__.'/getPimConnector_Archiver_InvalidItemXlsxWriterService.php')) && false ?: '_'});

return $instance;
