<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.result_record.hydrator.orm.object' shared service.

return $this->services['pim_datagrid.datasource.result_record.hydrator.orm.object'] = new \Oro\Bundle\PimDataGridBundle\Datasource\ResultRecord\Orm\ObjectHydrator();
