<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.identifier_field' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.identifier_field'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Field\IdentifierFilter(array(0 => 'identifier'), array(0 => 'STARTS WITH', 1 => 'CONTAINS', 2 => 'DOES NOT CONTAIN', 3 => '=', 4 => '!=', 5 => 'IN', 6 => 'NOT IN'));
