<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.connector.processor.mass_edit.product.update_value' shared service.

return $this->services['pim_enrich.connector.processor.mass_edit.product.update_value'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\Processor\MassEdit\UpdateProductValueProcessor(${($_ = isset($this->services['pim_catalog.updater.property_setter']) ? $this->services['pim_catalog.updater.property_setter'] : $this->load(__DIR__.'/getPimCatalog_Updater_PropertySetterService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.validator.product']) ? $this->services['pim_catalog.validator.product'] : $this->load(__DIR__.'/getPimCatalog_Validator_ProductService.php')) && false ?: '_'});
