<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.normalizer.product.product_value' shared service.

return $this->services['pim_datagrid.normalizer.product.product_value'] = new \Oro\Bundle\PimDataGridBundle\Normalizer\Product\ValueNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.product.product_value']) ? $this->services['pim_catalog.normalizer.standard.product.product_value'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_Product_ProductValueService.php')) && false ?: '_'});
