<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.normalizer.product_model' shared service.

return $this->services['pim_datagrid.normalizer.product_model'] = new \Oro\Bundle\PimDataGridBundle\Normalizer\ProductModelNormalizer(${($_ = isset($this->services['pim_catalog.filter.chained']) ? $this->services['pim_catalog.filter.chained'] : $this->load(__DIR__.'/getPimCatalog_Filter_ChainedService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.doctrine.query.find_variant_product_completeness']) ? $this->services['pim_catalog.doctrine.query.find_variant_product_completeness'] : $this->load(__DIR__.'/getPimCatalog_Doctrine_Query_FindVariantProductCompletenessService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.product_models.image_as_label']) ? $this->services['pim_catalog.product_models.image_as_label'] : $this->load(__DIR__.'/getPimCatalog_ProductModels_ImageAsLabelService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.normalizer.image']) ? $this->services['pim_enrich.normalizer.image'] : $this->load(__DIR__.'/getPimEnrich_Normalizer_ImageService.php')) && false ?: '_'});
