<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.parent' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.parent'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Field\ParentFilter(${($_ = isset($this->services['pim_catalog.repository.product_model']) ? $this->services['pim_catalog.repository.product_model'] : $this->load(__DIR__.'/getPimCatalog_Repository_ProductModelService.php')) && false ?: '_'}, array(0 => 'parent'), array(0 => 'IN', 1 => 'EMPTY', 2 => 'NOT EMPTY'));
