<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_pdf_generator.renderer.registry' shared service.

$this->services['pim_pdf_generator.renderer.registry'] = $instance = new \Akeneo\Pim\Enrichment\Bundle\PdfGeneration\Renderer\RendererRegistry();

$instance->addRenderer(${($_ = isset($this->services['pim_pdf_generator.renderer.product_pdf']) ? $this->services['pim_pdf_generator.renderer.product_pdf'] : $this->load(__DIR__.'/getPimPdfGenerator_Renderer_ProductPdfService.php')) && false ?: '_'});

return $instance;
