<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.connector.job.job_parameters.default_values_provider.product_mass_edit' shared service.

return $this->services['pim_enrich.connector.job.job_parameters.default_values_provider.product_mass_edit'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductMassEdit(array(0 => 'update_product_value', 1 => 'add_to_group', 2 => 'add_product_value', 3 => 'add_attribute_value', 4 => 'remove_product_value', 5 => 'move_to_category', 6 => 'add_to_category', 7 => 'remove_from_category', 8 => 'add_association', 9 => 'edit_common_attributes', 10 => 'add_to_existing_product_model', 11 => 'change_parent_product'));
