<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.product_and_product_model' shared service.

$this->services['pim_datagrid.datasource.product_and_product_model'] = $instance = new \Oro\Bundle\PimDataGridBundle\Datasource\ProductAndProductModelDatasource(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo.pim.enrichment.query.product_and_product_model_query_builder_from_size_factory.with_product_identifier_cursor']) ? $this->services['akeneo.pim.enrichment.query.product_and_product_model_query_builder_from_size_factory.with_product_identifier_cursor'] : $this->load(__DIR__.'/getAkeneo_Pim_Enrichment_Query_ProductAndProductModelQueryBuilderFromSizeFactory_WithProductIdentifierCursorService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid_serializer']) ? $this->services['pim_datagrid_serializer'] : $this->load(__DIR__.'/getPimDatagridSerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->load(__DIR__.'/getValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo.pim.enrichment.product.grid.query.fetch_product_and_product_model_rows']) ? $this->services['akeneo.pim.enrichment.product.grid.query.fetch_product_and_product_model_rows'] : $this->load(__DIR__.'/getAkeneo_Pim_Enrichment_Product_Grid_Query_FetchProductAndProductModelRowsService.php')) && false ?: '_'});

$instance->setMassActionRepository(${($_ = isset($this->services['pim_catalog.repository.product_mass_action']) ? $this->services['pim_catalog.repository.product_mass_action'] : $this->load(__DIR__.'/getPimCatalog_Repository_ProductMassActionService.php')) && false ?: '_'});

return $instance;
