<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.variant_navigation' shared service.

return $this->services['pim_enrich.normalizer.variant_navigation'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\VariantNavigationNormalizer(${($_ = isset($this->services['pim_catalog.repository.locale']) ? $this->services['pim_catalog.repository.locale'] : $this->getPimCatalog_Repository_LocaleService()) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.normalizer.entity_with_family_variant']) ? $this->services['pim_enrich.normalizer.entity_with_family_variant'] : $this->load(__DIR__.'/getPimEnrich_Normalizer_EntityWithFamilyVariantService.php')) && false ?: '_'});
