<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.job.job_parameters.constraint_collection_provider.compute_family_variant_structure_changes' shared service.

return $this->services['pim_catalog.job.job_parameters.constraint_collection_provider.compute_family_variant_structure_changes'] = new \Akeneo\Pim\Enrichment\Component\Product\Job\JobParameters\ConstraintCollectionProvider\ComputeFamilyVariantStructureChanges(array(0 => 'compute_family_variant_structure_changes'));
