<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.reader.file.csv_association' shared service.

return $this->services['pim_connector.reader.file.csv_association'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\File\Csv\ProductAssociationReader(${($_ = isset($this->services['pim_connector.reader.file.csv_iterator_factory']) ? $this->services['pim_connector.reader.file.csv_iterator_factory'] : $this->services['pim_connector.reader.file.csv_iterator_factory'] = new \Akeneo\Tool\Component\Connector\Reader\File\FileIteratorFactory('Akeneo\\Tool\\Component\\Connector\\Reader\\File\\FlatFileIterator', 'csv')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.array_converter.flat_to_standard.product_association']) ? $this->services['pim_connector.array_converter.flat_to_standard.product_association'] : $this->load(__DIR__.'/getPimConnector_ArrayConverter_FlatToStandard_ProductAssociationService.php')) && false ?: '_'});
