<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_dashboard.widget.last_operations' shared service.

return $this->services['pim_dashboard.widget.last_operations'] = new \Akeneo\Platform\Bundle\DashboardBundle\Widget\LastOperationsWidget(${($_ = isset($this->services['pim_import_export.manager.job_execution']) ? $this->services['pim_import_export.manager.job_execution'] : $this->load(__DIR__.'/getPimImportExport_Manager_JobExecutionService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.presenter.datetime']) ? $this->services['pim_catalog.localization.presenter.datetime'] : $this->load(__DIR__.'/getPimCatalog_Localization_Presenter_DatetimeService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['oro_security.security_facade']) ? $this->services['oro_security.security_facade'] : $this->getOroSecurity_SecurityFacadeService()) && false ?: '_'});
