<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_filter.product_in_group_filter' shared service.

return $this->services['pim_filter.product_in_group_filter'] = new \Oro\Bundle\PimFilterBundle\Filter\Product\InGroupFilter(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_filter.product_utility']) ? $this->services['pim_filter.product_utility'] : $this->services['pim_filter.product_utility'] = new \Oro\Bundle\PimFilterBundle\Filter\ProductFilterUtility()) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.datagrid.request.parameters_extractor']) ? $this->services['pim_datagrid.datagrid.request.parameters_extractor'] : $this->load(__DIR__.'/getPimDatagrid_Datagrid_Request_ParametersExtractorService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.doctrine.query.filter.object_code_resolver']) ? $this->services['pim_catalog.doctrine.query.filter.object_code_resolver'] : $this->load(__DIR__.'/getPimCatalog_Doctrine_Query_Filter_ObjectCodeResolverService.php')) && false ?: '_'});
