<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.factory.date' shared service.

return $this->services['pim_catalog.localization.factory.date'] = new \Akeneo\Tool\Component\Localization\Factory\DateFactory($this->parameters['pim_catalog.localization.factory.date.formats']);
