<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.doctrine.query.filter.date' shared service.

return $this->services['pim_catalog.doctrine.query.filter.date'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\DateFilter(${($_ = isset($this->services['pim_catalog.validator.helper.attribute']) ? $this->services['pim_catalog.validator.helper.attribute'] : $this->load(__DIR__.'/getPimCatalog_Validator_Helper_AttributeService.php')) && false ?: '_'}, array(0 => 'pim_catalog_date'), array(0 => '=', 1 => '<', 2 => '>', 3 => 'BETWEEN', 4 => 'NOT BETWEEN', 5 => 'EMPTY', 6 => 'NOT EMPTY', 7 => '!='));
