<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.localizer.converter' shared service.

return $this->services['pim_catalog.localization.localizer.converter'] = new \Akeneo\Pim\Enrichment\Component\Product\Localization\Localizer\AttributeConverter(${($_ = isset($this->services['pim_catalog.localization.localizer.registry']) ? $this->services['pim_catalog.localization.localizer.registry'] : $this->load(__DIR__.'/getPimCatalog_Localization_Localizer_RegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_AttributeService.php')) && false ?: '_'});
