<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.flat_to_standard.attribute_option' shared service.

return $this->services['pim_connector.array_converter.flat_to_standard.attribute_option'] = new \Akeneo\Pim\Structure\Component\ArrayConverter\FlatToStandard\AttributeOption(${($_ = isset($this->services['pim_catalog.repository.locale']) ? $this->services['pim_catalog.repository.locale'] : $this->getPimCatalog_Repository_LocaleService()) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.array_convertor.checker.fields_requirement']) ? $this->services['pim_connector.array_convertor.checker.fields_requirement'] : $this->services['pim_connector.array_convertor.checker.fields_requirement'] = new \Akeneo\Tool\Component\Connector\ArrayConverter\FieldsRequirementChecker()) && false ?: '_'});
