<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.id' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.id'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Field\IdFilter(array(0 => 'id'), array(0 => 'IN', 1 => 'NOT IN', 2 => '=', 3 => '!='));
