<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.normalizer.group_product' shared service.

return $this->services['pim_datagrid.normalizer.group_product'] = new \Oro\Bundle\PimDataGridBundle\Normalizer\GroupProductNormalizer(${($_ = isset($this->services['pim_catalog.filter.chained']) ? $this->services['pim_catalog.filter.chained'] : $this->load(__DIR__.'/getPimCatalog_Filter_ChainedService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.normalizer.image']) ? $this->services['pim_enrich.normalizer.image'] : $this->load(__DIR__.'/getPimEnrich_Normalizer_ImageService.php')) && false ?: '_'});
