<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.sorter.identifier' shared service.

return $this->services['pim_catalog.query.elasticsearch.sorter.identifier'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Sorter\IdentifierSorter(array(0 => 'identifier'), array(0 => 'pim_catalog_identifier'));
