<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.normalizer.storage.product.product_values' shared service.

if ($lazyLoad) {
    return $this->services['pim_catalog.normalizer.storage.product.product_values'] = $this->createProxy('ProductValuesNormalizer_8997cea', function () {
        return \ProductValuesNormalizer_8997cea::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load(__DIR__.'/getPimCatalog_Normalizer_Storage_Product_ProductValuesService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\ProductValuesNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.storage.product.product_value']) ? $this->services['pim_catalog.normalizer.storage.product.product_value'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Storage_Product_ProductValueService.php')) && false ?: '_'});
