<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.family_attribute_as_image' shared service.

return $this->services['pim_catalog.validator.constraint.family_attribute_as_image'] = new \Akeneo\Pim\Structure\Component\Validator\Constraints\FamilyAttributeAsImageValidator(array(0 => 'pim_catalog_image', 1 => 'pim_assets_collection'));
