<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.twig.category_extension' shared service.

return $this->services['pim_enrich.twig.category_extension'] = new \Akeneo\Pim\Enrichment\Bundle\Twig\CategoryExtension(${($_ = isset($this->services['pim_enrich.doctrine.counter.category_registry']) ? $this->services['pim_enrich.doctrine.counter.category_registry'] : $this->load(__DIR__.'/getPimEnrich_Doctrine_Counter_CategoryRegistryService.php')) && false ?: '_'}, 100);
