<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.connector.job.job_parameters.default_values_provider.product_csv_quick_export' shared service.

return $this->services['pim_enrich.connector.job.job_parameters.default_values_provider.product_csv_quick_export'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductQuickExport(${($_ = isset($this->services['akeneo_pim_enrichment.job.job_parameters.default_values_provider.simple_csv_export']) ? $this->services['akeneo_pim_enrichment.job.job_parameters.default_values_provider.simple_csv_export'] : $this->services['akeneo_pim_enrichment.job.job_parameters.default_values_provider.simple_csv_export'] = new \Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleCsvExport(array(0 => 'csv_group_export', 1 => 'csv_category_export'))) && false ?: '_'}, array(0 => 'csv_product_quick_export', 1 => 'csv_product_grid_context_quick_export'));
