<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.type.async_select' shared service.

return $this->services['pim_enrich.form.type.async_select'] = new \Akeneo\Platform\Bundle\UIBundle\Form\Type\AsyncSelectType(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, new \Akeneo\Platform\Bundle\UIBundle\Form\Factory\IdentifiableModelTransformerFactory('Akeneo\\Platform\\Bundle\\UIBundle\\Form\\Transformer\\IdentifiableModelTransformer'));
