<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.locale' shared service.

return $this->services['pim_catalog.updater.locale'] = new \Akeneo\Channel\Component\Updater\LocaleUpdater();
