<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.index_product_model_completedata' shared service.

return $this->services['pim_catalog.event_subscriber.index_product_model_completedata'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\IndexProductModelCompleteDataSubscriber(${($_ = isset($this->services['pim_catalog.elasticsearch.indexer.product_model']) ? $this->services['pim_catalog.elasticsearch.indexer.product_model'] : $this->load(__DIR__.'/getPimCatalog_Elasticsearch_Indexer_ProductModelService.php')) && false ?: '_'});
