<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.normalizer.standard.product.associations' shared service.

return $this->services['pim_catalog.normalizer.standard.product.associations'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\Product\AssociationsNormalizer(${($_ = isset($this->services['pim_catalog.query.get_associated_product_codes_by_product']) ? $this->services['pim_catalog.query.get_associated_product_codes_by_product'] : $this->load(__DIR__.'/getPimCatalog_Query_GetAssociatedProductCodesByProductService.php')) && false ?: '_'});
