<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.builder.version' shared service.

return $this->services['pim_versioning.builder.version'] = new \Akeneo\Tool\Bundle\VersioningBundle\Builder\VersionBuilder(${($_ = isset($this->services['pim_versioning.serializer']) ? $this->services['pim_versioning.serializer'] : $this->load(__DIR__.'/getPimVersioning_SerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_versioning.factory.version']) ? $this->services['pim_versioning.factory.version'] : $this->services['pim_versioning.factory.version'] = new \Akeneo\Tool\Bundle\VersioningBundle\Factory\VersionFactory('Akeneo\\Tool\\Component\\Versioning\\Model\\Version')) && false ?: '_'});
