<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.factory.product_model_from_size_cursor' shared service.

return $this->services['pim_catalog.factory.product_model_from_size_cursor'] = new \Akeneo\Tool\Bundle\ElasticsearchBundle\Cursor\FromSizeCursorFactory(${($_ = isset($this->services['akeneo_elasticsearch.client.product_model']) ? $this->services['akeneo_elasticsearch.client.product_model'] : $this->load(__DIR__.'/getAkeneoElasticsearch_Client_ProductModelService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.product_model']) ? $this->services['pim_catalog.repository.product_model'] : $this->load(__DIR__.'/getPimCatalog_Repository_ProductModelService.php')) && false ?: '_'}, 'Akeneo\\Tool\\Bundle\\ElasticsearchBundle\\Cursor\\FromSizeCursor', 100, 'pim_catalog_product');
