<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.extension.intl' shared service.

return $this->services['twig.extension.intl'] = new \Twig_Extensions_Extension_Intl();
