<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_xlsx_import' shared service.

return $this->services['akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_xlsx_import'] = new \Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxImport(array(0 => 'xlsx_attribute_import', 1 => 'xlsx_family_import', 2 => 'xlsx_family_variant_import', 3 => 'xlsx_association_type_import', 4 => 'xlsx_attribute_option_import', 5 => 'xlsx_attribute_group_import', 6 => 'xlsx_group_type_import'));
