<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_batch.job_repository' shared service.

return $this->services['akeneo_batch.job_repository'] = new \Akeneo\Tool\Bundle\BatchBundle\Job\DoctrineJobRepository(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, 'Akeneo\\Tool\\Component\\Batch\\Model\\JobExecution', 'Akeneo\\Tool\\Component\\Batch\\Model\\JobInstance', 'Akeneo\\Tool\\Bundle\\BatchBundle\\Job\\JobInstanceRepository');
