<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_elasticsearch.client.product' shared service.

return $this->services['akeneo_elasticsearch.client.product'] = new \Akeneo\Tool\Bundle\ElasticsearchBundle\Client(${($_ = isset($this->services['akeneo_elasticsearch.client_builder']) ? $this->services['akeneo_elasticsearch.client_builder'] : $this->services['akeneo_elasticsearch.client_builder'] = new \Elasticsearch\ClientBuilder()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_elasticsearch.client.product.index_configuration.files']) ? $this->services['akeneo_elasticsearch.client.product.index_configuration.files'] : $this->services['akeneo_elasticsearch.client.product.index_configuration.files'] = new \Akeneo\Tool\Bundle\ElasticsearchBundle\IndexConfiguration\Loader($this->getParameter('elasticsearch_index_configuration_files'))) && false ?: '_'}, array(0 => 'elastic:changeme@elasticsearch:9200'), 'akeneo_pim_product');
