<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.lessphp' shared service.

include_once ($this->targetDirs[3].'/app/../vendor/leafo/lessphp/lessc.inc.php');

$this->services['assetic.filter.lessphp'] = $instance = new \Assetic\Filter\LessphpFilter();

$instance->setPresets(array());
$instance->setLoadPaths(array());
$instance->setFormatter(NULL);
$instance->setPreserveComments(NULL);

return $instance;
