<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.logger.batch' shared service.

$this->services['monolog.logger.batch'] = $instance = new \Symfony\Bridge\Monolog\Logger('batch');

$instance->pushHandler(${($_ = isset($this->services['monolog.handler.console']) ? $this->services['monolog.handler.console'] : $this->getMonolog_Handler_ConsoleService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.main']) ? $this->services['monolog.handler.main'] : $this->getMonolog_Handler_MainService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['akeneo_batch.logger.batch_log_handler']) ? $this->services['akeneo_batch.logger.batch_log_handler'] : $this->load(__DIR__.'/getAkeneoBatch_Logger_BatchLogHandlerService.php')) && false ?: '_'});

return $instance;
