<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_config.global' shared service.

return $this->services['oro_config.global'] = new \Oro\Bundle\ConfigBundle\Config\ConfigManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, array('pim_analytics' => array('version_update' => array('value' => true, 'scope' => 'app')), 'pim_ui' => array('loading_message_enabled' => array('value' => false, 'scope' => 'app'), 'language' => array('value' => 'en', 'scope' => 'app'))));
