<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_filter.twig.extension.render_layout' shared service.

return $this->services['oro_filter.twig.extension.render_layout'] = new \Oro\Bundle\FilterBundle\Twig\RenderLayoutExtension('PimFilterBundle:Filter:pim-layout.js.twig');
