<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_filter.form.type.filter.metric' shared service.

return $this->services['pim_filter.form.type.filter.metric'] = new \Oro\Bundle\PimFilterBundle\Form\Type\Filter\MetricFilterType();
