<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_installer.step.fixtures_job_yml.import' shared service.

$a = ${($_ = isset($this->services['pim_connector.processor.denormalization.job_instance']) ? $this->services['pim_connector.processor.denormalization.job_instance'] : $this->load(__DIR__.'/getPimConnector_Processor_Denormalization_JobInstanceService.php')) && false ?: '_'};

if (isset($this->services['pim_installer.step.fixtures_job_yml.import'])) {
    return $this->services['pim_installer.step.fixtures_job_yml.import'];
}

return $this->services['pim_installer.step.fixtures_job_yml.import'] = new \Akeneo\Tool\Component\Batch\Step\ItemStep('import', ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->load(__DIR__.'/getAkeneoBatch_JobRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.reader.file.yaml_job_instance']) ? $this->services['pim_connector.reader.file.yaml_job_instance'] : $this->load(__DIR__.'/getPimConnector_Reader_File_YamlJobInstanceService.php')) && false ?: '_'}, $a, ${($_ = isset($this->services['pim_connector.writer.database.job_instance']) ? $this->services['pim_connector.writer.database.job_instance'] : $this->load(__DIR__.'/getPimConnector_Writer_Database_JobInstanceService.php')) && false ?: '_'});
