<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_localization.twig.attribute_extension' shared service.

return $this->services['pim_localization.twig.attribute_extension'] = new \Akeneo\Platform\Bundle\UIBundle\Twig\AttributeExtension(${($_ = isset($this->services['pim_catalog.localization.presenter.date']) ? $this->services['pim_catalog.localization.presenter.date'] : $this->load(__DIR__.'/getPimCatalog_Localization_Presenter_DateService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.presenter.datetime']) ? $this->services['pim_catalog.localization.presenter.datetime'] : $this->load(__DIR__.'/getPimCatalog_Localization_Presenter_DatetimeService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.resolver.locale']) ? $this->services['pim_enrich.resolver.locale'] : $this->load(__DIR__.'/getPimEnrich_Resolver_LocaleService.php')) && false ?: '_'});
