<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.category' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.category'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Field\CategoryFilter(${($_ = isset($this->services['pim_catalog.repository.category']) ? $this->services['pim_catalog.repository.category'] : $this->getPimCatalog_Repository_CategoryService()) && false ?: '_'}, array(0 => 'categories'), array(0 => 'IN', 1 => 'NOT IN', 2 => 'UNCLASSIFIED', 3 => 'IN OR UNCLASSIFIED', 4 => 'IN CHILDREN', 5 => 'NOT IN CHILDREN'));
