<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.event_subscriber.group' shared service.

return $this->services['pim_user.event_subscriber.group'] = new \Akeneo\UserManagement\Bundle\EventListener\GroupSubscriber();
