<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.presenter.product_value.boolean' shared service.

return $this->services['pim_catalog.localization.presenter.product_value.boolean'] = new \Akeneo\Tool\Component\Localization\Presenter\BooleanPresenter(array(0 => 'pim_catalog_boolean'));
