<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_external_api_exception_serializer' shared service.

return $this->services['pim_external_api_exception_serializer'] = new \Symfony\Component\Serializer\Serializer(array(0 => ${($_ = isset($this->services['pim_api.normalizer.exception.documented']) ? $this->services['pim_api.normalizer.exception.documented'] : $this->services['pim_api.normalizer.exception.documented'] = new \Akeneo\Tool\Component\Api\Normalizer\Exception\DocumentedNormalizer()) && false ?: '_'}, 1 => ${($_ = isset($this->services['pim_api.normalizer.exception.violation']) ? $this->services['pim_api.normalizer.exception.violation'] : $this->load(__DIR__.'/getPimApi_Normalizer_Exception_ViolationService.php')) && false ?: '_'}, 2 => ${($_ = isset($this->services['fos_rest.serializer.exception_normalizer.symfony']) ? $this->services['fos_rest.serializer.exception_normalizer.symfony'] : $this->load(__DIR__.'/getFosRest_Serializer_ExceptionNormalizer_SymfonyService.php')) && false ?: '_'}), array(0 => new \Symfony\Component\Serializer\Encoder\JsonEncoder()));
