<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.type.group' shared service.

return $this->services['pim_enrich.form.type.group'] = new \Akeneo\Pim\Enrichment\Bundle\Form\Type\GroupType('Akeneo\\Pim\\Structure\\Component\\Model\\Attribute', 'Akeneo\\Pim\\Enrichment\\Component\\Product\\Model\\Group');
