<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_ui.form.type.switch' shared service.

return $this->services['pim_ui.form.type.switch'] = new \Akeneo\Platform\Bundle\UIBundle\Form\Type\SwitchType();
