<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.manager.datagrid_view' shared service.

return $this->services['pim_datagrid.manager.datagrid_view'] = new \Oro\Bundle\PimDataGridBundle\Manager\DatagridViewManager(${($_ = isset($this->services['pim_datagrid.repository.datagrid_view']) ? $this->services['pim_datagrid.repository.datagrid_view'] : $this->load(__DIR__.'/getPimDatagrid_Repository_DatagridViewService.php')) && false ?: '_'}, ${($_ = isset($this->services['oro_datagrid.datagrid.manager']) ? $this->services['oro_datagrid.datagrid.manager'] : $this->services['oro_datagrid.datagrid.manager'] = new \Oro\Bundle\DataGridBundle\Datagrid\Manager($this)) && false ?: '_'});
