<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.standard_to_flat.product_localized' shared service.

return $this->services['pim_connector.array_converter.standard_to_flat.product_localized'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\ArrayConverter\StandardToFlat\ProductLocalized(${($_ = isset($this->services['pim_connector.array_converter.standard_to_flat.product']) ? $this->services['pim_connector.array_converter.standard_to_flat.product'] : $this->load(__DIR__.'/getPimConnector_ArrayConverter_StandardToFlat_ProductService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.localizer.converter']) ? $this->services['pim_catalog.localization.localizer.converter'] : $this->load(__DIR__.'/getPimCatalog_Localization_Localizer_ConverterService.php')) && false ?: '_'});
