<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datagrid.configuration.product.sorters_configurator' shared service.

return $this->services['pim_datagrid.datagrid.configuration.product.sorters_configurator'] = new \Oro\Bundle\PimDataGridBundle\Datagrid\Configuration\Product\SortersConfigurator(${($_ = isset($this->services['pim_datagrid.datagrid.configuration.product.configuration_registry']) ? $this->services['pim_datagrid.datagrid.configuration.product.configuration_registry'] : $this->load(__DIR__.'/getPimDatagrid_Datagrid_Configuration_Product_ConfigurationRegistryService.php')) && false ?: '_'});
