<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_installer.install_status_manager' shared service.

return $this->services['pim_installer.install_status_manager'] = new \Akeneo\Platform\Bundle\InstallerBundle\InstallStatusManager\InstallStatusManager(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'akeneo_pim');
