<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.factory.user' shared service.

return $this->services['pim_user.factory.user'] = new \Akeneo\UserManagement\Component\Factory\UserFactory(${($_ = isset($this->services['pim_catalog.repository.locale']) ? $this->services['pim_catalog.repository.locale'] : $this->getPimCatalog_Repository_LocaleService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.channel']) ? $this->services['pim_catalog.repository.channel'] : $this->getPimCatalog_Repository_ChannelService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.category']) ? $this->services['pim_catalog.repository.category'] : $this->getPimCatalog_Repository_CategoryService()) && false ?: '_'}, ${($_ = isset($this->services['pim_user.repository.group']) ? $this->services['pim_user.repository.group'] : $this->load(__DIR__.'/getPimUser_Repository_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_user.repository.role']) ? $this->services['pim_user.repository.role'] : $this->load(__DIR__.'/getPimUser_Repository_RoleService.php')) && false ?: '_'}, 'Akeneo\\UserManagement\\Component\\Model\\User');
