<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.family' shared service.

$a = ${($_ = isset($this->services['pim_enrich.repository.family']) ? $this->services['pim_enrich.repository.family'] : $this->load(__DIR__.'/getPimEnrich_Repository_FamilyService.php')) && false ?: '_'};

return $this->services['pim_datagrid.datasource.family'] = new \Oro\Bundle\PimDataGridBundle\Datasource\FamilyDatasource($a, $a, ${($_ = isset($this->services['pim_datagrid.datasource.result_record.hydrator.default']) ? $this->services['pim_datagrid.datasource.result_record.hydrator.default'] : $this->services['pim_datagrid.datasource.result_record.hydrator.default'] = new \Oro\Bundle\PimDataGridBundle\Datasource\ResultRecord\Orm\ResultRecordHydrator()) && false ?: '_'});
