<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.job.xlsx_product_grid_context_quick_export' shared service.

return $this->services['pim_enrich.job.xlsx_product_grid_context_quick_export'] = new \Akeneo\Tool\Component\Batch\Job\Job('xlsx_product_grid_context_quick_export', ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->load(__DIR__.'/getAkeneoBatch_JobRepositoryService.php')) && false ?: '_'}, array(0 => ${($_ = isset($this->services['pim_enrich.step.xlsx_product.quick_export']) ? $this->services['pim_enrich.step.xlsx_product.quick_export'] : $this->load(__DIR__.'/getPimEnrich_Step_XlsxProduct_QuickExportService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['pim_enrich.step.xlsx_product_model.quick_export']) ? $this->services['pim_enrich.step.xlsx_product_model.quick_export'] : $this->load(__DIR__.'/getPimEnrich_Step_XlsxProductModel_QuickExportService.php')) && false ?: '_'}));
