<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.view_element.user.tab.group_and_role' shared service.

$this->services['pim_user.view_element.user.tab.group_and_role'] = $instance = new \Akeneo\Platform\Bundle\UIBundle\ViewElement\BaseViewElement('pim_user.user.tabs.group_and_role', 'PimUserBundle:User:Tab/group_and_role.html.twig');

$instance->addVisibilityChecker(${($_ = isset($this->services['pim_user.view_element.visibility_checker.groups_and_roles']) ? $this->services['pim_user.view_element.visibility_checker.groups_and_roles'] : $this->services['pim_user.view_element.visibility_checker.groups_and_roles'] = new \Akeneo\UserManagement\Bundle\ViewElement\Checker\GroupsAndRolesVisibilityChecker()) && false ?: '_'});

return $instance;
