<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.writer.file.media_exporter_path_generator' shared service.

return $this->services['pim_connector.writer.file.media_exporter_path_generator'] = new \Akeneo\Tool\Component\Connector\Writer\File\MediaExporterPathGenerator();
