<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_reference_data.repository_resolver' shared service.

return $this->services['pim_reference_data.repository_resolver'] = new \Akeneo\Pim\Enrichment\Bundle\Doctrine\ReferenceDataRepositoryResolver(${($_ = isset($this->services['pim_reference_data.registry']) ? $this->services['pim_reference_data.registry'] : $this->services['pim_reference_data.registry'] = new \Akeneo\Pim\Structure\Component\ReferenceData\ConfigurationRegistry()) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
