<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_analytics.data_collector.storage' shared service.

return $this->services['pim_analytics.data_collector.storage'] = new \Akeneo\Platform\Bundle\AnalyticsBundle\DataCollector\StorageDataCollector(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
