<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.processor.denormalization.user' shared service.

return $this->services['pim_connector.processor.denormalization.user'] = new \Akeneo\Tool\Component\Connector\Processor\Denormalization\Processor(${($_ = isset($this->services['pim_user.repository.user']) ? $this->services['pim_user.repository.user'] : $this->load(__DIR__.'/getPimUser_Repository_UserService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_user.factory.user']) ? $this->services['pim_user.factory.user'] : $this->load(__DIR__.'/getPimUser_Factory_UserService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_user.updater.user']) ? $this->services['pim_user.updater.user'] : $this->load(__DIR__.'/getPimUser_Updater_UserService.php')) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->load(__DIR__.'/getValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'});
