<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.normalizer.indexing_product_and_product_model.product' shared service.

return $this->services['pim_catalog.normalizer.indexing_product_and_product_model.product'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Indexing\ProductAndProductModel\ProductNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.indexing_product_and_product_model.product.properties']) ? $this->services['pim_catalog.normalizer.indexing_product_and_product_model.product.properties'] : $this->services['pim_catalog.normalizer.indexing_product_and_product_model.product.properties'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Indexing\ProductAndProductModel\ProductPropertiesNormalizer()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes']) ? $this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] : $this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] = new \Akeneo\Pim\Enrichment\Component\Product\EntityWithFamilyVariant\EntityWithFamilyVariantAttributesProvider()) && false ?: '_'});
