<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.validator.constraint.date_format' shared service.

return $this->services['pim_catalog.localization.validator.constraint.date_format'] = new \Akeneo\Tool\Component\Localization\Validator\Constraints\DateFormatValidator(${($_ = isset($this->services['pim_catalog.localization.factory.date']) ? $this->services['pim_catalog.localization.factory.date'] : $this->load(__DIR__.'/getPimCatalog_Localization_Factory_DateService.php')) && false ?: '_'});
