<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.category' shared service.

return $this->services['pim_enrich.normalizer.category'] = new \Akeneo\Pim\Enrichment\Component\Category\Normalizer\InternalApi\CategoryNormalizer(${($_ = isset($this->services['pim_standard_format_serializer']) ? $this->services['pim_standard_format_serializer'] : $this->load(__DIR__.'/getPimStandardFormatSerializerService.php')) && false ?: '_'});
