<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.copier.registry' shared service.

$this->services['pim_catalog.updater.copier.registry'] = $instance = new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\CopierRegistry(${($_ = isset($this->services['pim_catalog.repository.cached_attribute']) ? $this->services['pim_catalog.repository.cached_attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedAttributeService.php')) && false ?: '_'});

$a = ${($_ = isset($this->services['pim_catalog.builder.entity_with_values']) ? $this->services['pim_catalog.builder.entity_with_values'] : $this->load(__DIR__.'/getPimCatalog_Builder_EntityWithValuesService.php')) && false ?: '_'};
$b = ${($_ = isset($this->services['pim_catalog.validator.helper.attribute']) ? $this->services['pim_catalog.validator.helper.attribute'] : $this->load(__DIR__.'/getPimCatalog_Validator_Helper_AttributeService.php')) && false ?: '_'};
$c = ${($_ = isset($this->services['pim_standard_format_serializer']) ? $this->services['pim_standard_format_serializer'] : $this->load(__DIR__.'/getPimStandardFormatSerializerService.php')) && false ?: '_'};
$d = ${($_ = isset($this->services['akeneo_file_storage.file_storage.file.file_fetcher']) ? $this->services['akeneo_file_storage.file_storage.file.file_fetcher'] : $this->load(__DIR__.'/getAkeneoFileStorage_FileStorage_File_FileFetcherService.php')) && false ?: '_'};
$e = ${($_ = isset($this->services['akeneo_file_storage.file_storage.file.file_storer']) ? $this->services['akeneo_file_storage.file_storage.file.file_storer'] : $this->load(__DIR__.'/getAkeneoFileStorage_FileStorage_File_FileStorerService.php')) && false ?: '_'};
$f = ${($_ = isset($this->services['akeneo_file_storage.file_storage.filesystem_provider']) ? $this->services['akeneo_file_storage.file_storage.filesystem_provider'] : $this->load(__DIR__.'/getAkeneoFileStorage_FileStorage_FilesystemProviderService.php')) && false ?: '_'};

$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_text'), array(0 => 'pim_catalog_text')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\MediaAttributeCopier($a, $b, $d, $e, $f, array(0 => 'pim_catalog_image'), array(0 => 'pim_catalog_image')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\MediaAttributeCopier($a, $b, $d, $e, $f, array(0 => 'pim_catalog_file'), array(0 => 'pim_catalog_file')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_textarea'), array(0 => 'pim_catalog_textarea')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_boolean'), array(0 => 'pim_catalog_boolean')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_number'), array(0 => 'pim_catalog_number')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_date'), array(0 => 'pim_catalog_date')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\MetricAttributeCopier($a, $b, $c, array(0 => 'pim_catalog_metric'), array(0 => 'pim_catalog_metric')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_simpleselect'), array(0 => 'pim_catalog_simpleselect')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_multiselect'), array(0 => 'pim_catalog_multiselect')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\AttributeCopier($a, $b, $c, array(0 => 'pim_catalog_price_collection'), array(0 => 'pim_catalog_price_collection')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\ReferenceDataAttributeCopier($a, $b, array(0 => 'pim_reference_data_simpleselect'), array(0 => 'pim_reference_data_simpleselect')));
$instance->register(new \Akeneo\Pim\Enrichment\Component\Product\Updater\Copier\ReferenceDataCollectionAttributeCopier($a, $b, array(0 => 'pim_reference_data_multiselect'), array(0 => 'pim_reference_data_multiselect')));

return $instance;
