<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.type.group_type' shared service.

return $this->services['pim_enrich.form.type.group_type'] = new \Akeneo\Pim\Structure\Bundle\Form\Type\GroupTypeType('Akeneo\\Pim\\Structure\\Component\\Model\\GroupType');
