<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.normalizer.user' shared service.

return $this->services['pim_user.normalizer.user'] = new \Akeneo\UserManagement\Component\Normalizer\UserNormalizer(${($_ = isset($this->services['serializer.normalizer.datetime']) ? $this->services['serializer.normalizer.datetime'] : $this->services['serializer.normalizer.datetime'] = new \Symfony\Component\Serializer\Normalizer\DateTimeNormalizer()) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.normalizer.file']) ? $this->services['pim_enrich.normalizer.file'] : $this->services['pim_enrich.normalizer.file'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\FileNormalizer()) && false ?: '_'}, ${($_ = isset($this->services['oro_security.security_facade']) ? $this->services['oro_security.security_facade'] : $this->getOroSecurity_SecurityFacadeService()) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.repository.datagrid_view']) ? $this->services['pim_datagrid.repository.datagrid_view'] : $this->load(__DIR__.'/getPimDatagrid_Repository_DatagridViewService.php')) && false ?: '_'}, array());
