<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_serializer' shared service.

return $this->services['pim_serializer'] = new \Symfony\Component\Serializer\Serializer(array(0 => ${($_ = isset($this->services['pim_import_export.normalizer.job_execution']) ? $this->services['pim_import_export.normalizer.job_execution'] : $this->load(__DIR__.'/getPimImportExport_Normalizer_JobExecutionService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['pim_import_export.normalizer.step_execution']) ? $this->services['pim_import_export.normalizer.step_execution'] : $this->load(__DIR__.'/getPimImportExport_Normalizer_StepExecutionService.php')) && false ?: '_'}), array(0 => ${($_ = isset($this->services['serializer.encoder.json']) ? $this->services['serializer.encoder.json'] : $this->services['serializer.encoder.json'] = new \Symfony\Component\Serializer\Encoder\JsonEncoder()) && false ?: '_'}));
