<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.filter.product.attribute_dumper' shared service.

return $this->services['pim_catalog.query.filter.product.attribute_dumper'] = new \Akeneo\Pim\Enrichment\Bundle\Command\ProductQueryHelp\AttributeFilterDumper(${($_ = isset($this->services['pim_catalog.query.filter.product_registry']) ? $this->services['pim_catalog.query.filter.product_registry'] : $this->load(__DIR__.'/getPimCatalog_Query_Filter_ProductRegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_AttributeService.php')) && false ?: '_'});
