<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datagrid.configuration.product.group_columns_configurator' shared service.

return $this->services['pim_datagrid.datagrid.configuration.product.group_columns_configurator'] = new \Oro\Bundle\PimDataGridBundle\Datagrid\Configuration\Product\GroupColumnsConfigurator(${($_ = isset($this->services['pim_datagrid.datagrid.configuration.product.configuration_registry']) ? $this->services['pim_datagrid.datagrid.configuration.product.configuration_registry'] : $this->load(__DIR__.'/getPimDatagrid_Datagrid_Configuration_Product_ConfigurationRegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['oro_datagrid.datagrid.request_params']) ? $this->services['oro_datagrid.datagrid.request_params'] : $this->load(__DIR__.'/getOroDatagrid_Datagrid_RequestParamsService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.group']) ? $this->services['pim_catalog.repository.group'] : $this->load(__DIR__.'/getPimCatalog_Repository_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
