<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.group_product' shared service.

return $this->services['pim_datagrid.datasource.group_product'] = new \Oro\Bundle\PimDataGridBundle\Datasource\ProductDatasource(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.query.product_query_builder_from_size_factory']) ? $this->services['pim_catalog.query.product_query_builder_from_size_factory'] : $this->load(__DIR__.'/getPimCatalog_Query_ProductQueryBuilderFromSizeFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.normalizer.group_product']) ? $this->services['pim_datagrid.normalizer.group_product'] : $this->load(__DIR__.'/getPimDatagrid_Normalizer_GroupProductService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber']) ? $this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber'] : $this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber'] = new \Oro\Bundle\PimDataGridBundle\EventSubscriber\FilterEntityWithValuesSubscriber()) && false ?: '_'});
