<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_ui.controller.ajax_option' shared service.

return $this->services['pim_ui.controller.ajax_option'] = new \Akeneo\Platform\Bundle\UIBundle\Controller\AjaxOptionController(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['pim_reference_data.registry']) ? $this->services['pim_reference_data.registry'] : $this->services['pim_reference_data.registry'] = new \Akeneo\Pim\Structure\Component\ReferenceData\ConfigurationRegistry()) && false ?: '_'});
