<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_dashboard.widget.completeness' shared service.

return $this->services['pim_dashboard.widget.completeness'] = new \Akeneo\Pim\Enrichment\Bundle\Widget\CompletenessWidget(${($_ = isset($this->services['pim_user.context.user']) ? $this->services['pim_user.context.user'] : $this->getPimUser_Context_UserService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo.pim.enrichment.follow_up.completeness_widget_query']) ? $this->services['akeneo.pim.enrichment.follow_up.completeness_widget_query'] : $this->load(__DIR__.'/getAkeneo_Pim_Enrichment_FollowUp_CompletenessWidgetQueryService.php')) && false ?: '_'});
