<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.adapter.items_counter' shared service.

return $this->services['pim_datagrid.adapter.items_counter'] = new \Oro\Bundle\PimDataGridBundle\Adapter\ItemsCounter(${($_ = isset($this->services['pim_enrich.doctrine.query.count_impacted_products']) ? $this->services['pim_enrich.doctrine.query.count_impacted_products'] : $this->load(__DIR__.'/getPimEnrich_Doctrine_Query_CountImpactedProductsService.php')) && false ?: '_'});
