<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.metric' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.metric'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\MetricFilter(${($_ = isset($this->services['pim_catalog.validator.helper.attribute']) ? $this->services['pim_catalog.validator.helper.attribute'] : $this->load(__DIR__.'/getPimCatalog_Validator_Helper_AttributeService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_measure.manager']) ? $this->services['akeneo_measure.manager'] : $this->load(__DIR__.'/getAkeneoMeasure_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_measure.measure_converter']) ? $this->services['akeneo_measure.measure_converter'] : $this->load(__DIR__.'/getAkeneoMeasure_MeasureConverterService.php')) && false ?: '_'}, array(0 => 'pim_catalog_metric'), array(0 => '<', 1 => '<=', 2 => '=', 3 => '!=', 4 => '>=', 5 => '>', 6 => 'EMPTY', 7 => 'EMPTY FOR CURRENCY', 8 => 'EMPTY ON ALL CURRENCIES', 9 => 'NOT EMPTY', 10 => 'NOT EMPTY ON AT LEAST ONE CURRENCY', 11 => 'NOT EMPTY FOR CURRENCY'));
