<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.handler.group' shared service.

return $this->services['pim_enrich.form.handler.group'] = new \Akeneo\Pim\Enrichment\Bundle\Form\Handler\GroupHandler(${($_ = isset($this->services['pim_enrich.form.group']) ? $this->services['pim_enrich.form.group'] : $this->load(__DIR__.'/getPimEnrich_Form_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.saver.group']) ? $this->services['pim_catalog.saver.group'] : $this->load(__DIR__.'/getPimCatalog_Saver_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.product']) ? $this->services['pim_catalog.repository.product'] : $this->load(__DIR__.'/getPimCatalog_Repository_ProductService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.localizer.converter']) ? $this->services['pim_catalog.localization.localizer.converter'] : $this->load(__DIR__.'/getPimCatalog_Localization_Localizer_ConverterService.php')) && false ?: '_'});
