<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.extension.pager.orm.pager' shared service.

return $this->services['pim_datagrid.extension.pager.orm.pager'] = new \Oro\Bundle\PimDataGridBundle\Extension\Pager\Orm\Pager();
