<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.only_expected_attributes' shared service.

return $this->services['pim_catalog.validator.constraint.only_expected_attributes'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\OnlyExpectedAttributesValidator(${($_ = isset($this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes']) ? $this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] : $this->services['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] = new \Akeneo\Pim\Enrichment\Component\Product\EntityWithFamilyVariant\EntityWithFamilyVariantAttributesProvider()) && false ?: '_'});
