<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_filter.product_value_date' shared service.

return $this->services['pim_filter.product_value_date'] = new \Oro\Bundle\PimFilterBundle\Filter\ProductValue\DateRangeFilter(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_filter.product_utility']) ? $this->services['pim_filter.product_utility'] : $this->services['pim_filter.product_utility'] = new \Oro\Bundle\PimFilterBundle\Filter\ProductFilterUtility()) && false ?: '_'});
