<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.attribute_option_value' shared service.

return $this->services['pim_enrich.normalizer.attribute_option_value'] = new \Akeneo\Pim\Structure\Component\Normalizer\InternalApi\AttributeOptionValueNormalizer();
