<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.twig.locale_extension' shared service.

return $this->services['pim_enrich.twig.locale_extension'] = new \Akeneo\Channel\Bundle\Twig\LocaleExtension(${($_ = isset($this->services['pim_user.context.user']) ? $this->services['pim_user.context.user'] : $this->getPimUser_Context_UserService()) && false ?: '_'});
