<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.update_guesser.associations' shared service.

return $this->services['pim_versioning.update_guesser.associations'] = new \Akeneo\Tool\Bundle\VersioningBundle\UpdateGuesser\AssociationsUpdateGuesser($this->parameters['pim_versioning.versionable_entities']);
