<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_import_export.datagrid.provider.job' shared service.

return $this->services['pim_import_export.datagrid.provider.job'] = new \Akeneo\Platform\Bundle\ImportExportBundle\Datagrid\JobDatagridProvider(${($_ = isset($this->services['akeneo_batch.job.job_registry']) ? $this->services['akeneo_batch.job.job_registry'] : $this->load(__DIR__.'/getAkeneoBatch_Job_JobRegistryService.php')) && false ?: '_'});
