<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.filter.product_value.locale' shared service.

return $this->services['pim_enrich.filter.product_value.locale'] = new \Akeneo\Pim\Enrichment\Bundle\Filter\ProductValueLocaleFilter();
