<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.command.cleaner.wrong_value_on_variant_product' shared service.

return $this->services['pim_catalog.command.cleaner.wrong_value_on_variant_product'] = new \Akeneo\Pim\Enrichment\Bundle\Command\Cleaner\WrongValuesOnVariantProductCleaner();
