<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.writer.file.product_model.flat_item_buffer_flusher' shared service.

return $this->services['pim_connector.writer.file.product_model.flat_item_buffer_flusher'] = new \Akeneo\Tool\Component\Connector\Writer\File\FlatItemBufferFlusher(${($_ = isset($this->services['pim_connector.writer.file.product_model.column_sorter']) ? $this->services['pim_connector.writer.file.product_model.column_sorter'] : $this->load(__DIR__.'/getPimConnector_Writer_File_ProductModel_ColumnSorterService.php')) && false ?: '_'});
