<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.sorter.family' shared service.

return $this->services['pim_catalog.query.elasticsearch.sorter.family'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Sorter\Field\FamilySorter(${($_ = isset($this->services['pim_catalog.repository.locale']) ? $this->services['pim_catalog.repository.locale'] : $this->getPimCatalog_Repository_LocaleService()) && false ?: '_'}, array(0 => 'family'));
