<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.normalizer.storage.product.associations' shared service.

return $this->services['pim_catalog.normalizer.storage.product.associations'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\AssociationsNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.product.associations']) ? $this->services['pim_catalog.normalizer.standard.product.associations'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_Product_AssociationsService.php')) && false ?: '_'});
