<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.compute_product_raw_values' shared service.

return $this->services['pim_catalog.event_subscriber.compute_product_raw_values'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\ComputeEntityRawValuesSubscriber(${($_ = isset($this->services['pim_storage_serializer']) ? $this->services['pim_storage_serializer'] : $this->load(__DIR__.'/getPimStorageSerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_AttributeService.php')) && false ?: '_'});
