<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.invalid_variant_product_parent' shared service.

return $this->services['pim_catalog.validator.constraint.invalid_variant_product_parent'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\VariantProductParentValidator();
