<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_pdf_generator.builder.dompdf' shared service.

return $this->services['pim_pdf_generator.builder.dompdf'] = new \Akeneo\Pim\Enrichment\Bundle\PdfGeneration\Builder\DompdfBuilder(($this->targetDirs[3].'/app'));
