<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.step.xlsx_family.compute_data_related_to_family_products' shared service.

return $this->services['pim_connector.step.xlsx_family.compute_data_related_to_family_products'] = new \Akeneo\Tool\Component\Connector\Step\TaskletStep('compute_data_related_to_family_products', ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->load(__DIR__.'/getAkeneoBatch_JobRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.tasklet.xlsx_family.compute_data_related_to_family_products']) ? $this->services['pim_connector.tasklet.xlsx_family.compute_data_related_to_family_products'] : $this->load(__DIR__.'/getPimConnector_Tasklet_XlsxFamily_ComputeDataRelatedToFamilyProductsService.php')) && false ?: '_'});
