<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.elasticsearch.filter.text' shared service.

return $this->services['pim_catalog.query.elasticsearch.filter.text'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\TextFilter(${($_ = isset($this->services['pim_catalog.validator.helper.attribute']) ? $this->services['pim_catalog.validator.helper.attribute'] : $this->load(__DIR__.'/getPimCatalog_Validator_Helper_AttributeService.php')) && false ?: '_'}, array(0 => 'pim_catalog_text'), array(0 => 'STARTS WITH', 1 => 'CONTAINS', 2 => 'DOES NOT CONTAIN', 3 => '=', 4 => 'EMPTY', 5 => 'NOT EMPTY', 6 => '!='));
