<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.acl.provider' shared service.

return $this->services['security.acl.provider'] = new \Oro\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['oro_security.acl.permission_granting_strategy']) ? $this->services['oro_security.acl.permission_granting_strategy'] : $this->load(__DIR__.'/getOroSecurity_Acl_PermissionGrantingStrategyService.php')) && false ?: '_'}, array('class_table_name' => 'acl_classes', 'entry_table_name' => 'acl_entries', 'oid_table_name' => 'acl_object_identities', 'oid_ancestors_table_name' => 'acl_object_identity_ancestors', 'sid_table_name' => 'acl_security_identities'), ${($_ = isset($this->services['security.acl.cache']) ? $this->services['security.acl.cache'] : $this->load(__DIR__.'/getSecurity_Acl_CacheService.php')) && false ?: '_'});
