<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxchzqg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxchzqg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSxchzqg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSxchzqg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSxchzqg\appProdProjectContainer(array(
    'container.build_hash' => 'Sxchzqg',
    'container.build_id' => 'e8bfc62d',
    'container.build_time' => 1549288944,
));
