<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo.pim.enrichment.product.grid.query.fetch_product_model_rows_from_codes' shared service.

return $this->services['akeneo.pim.enrichment.product.grid.query.fetch_product_model_rows_from_codes'] = new \Akeneo\Pim\Enrichment\Bundle\Storage\Sql\ProductGrid\FetchProductModelRowsFromCodes(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.factory.value_collection']) ? $this->services['pim_catalog.factory.value_collection'] : $this->load(__DIR__.'/getPimCatalog_Factory_ValueCollectionService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo.pim.enrichment.product.grid.query.product_model_images_from_codes']) ? $this->services['akeneo.pim.enrichment.product.grid.query.product_model_images_from_codes'] : $this->load(__DIR__.'/getAkeneo_Pim_Enrichment_Product_Grid_Query_ProductModelImagesFromCodesService.php')) && false ?: '_'});
