<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.pim_array' shared service.

return $this->services['doctrine_cache.providers.pim_array'] = new \Doctrine\Common\Cache\ArrayCache();
