<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.normalizer.association_type' shared service.

return $this->services['pim_api.normalizer.association_type'] = new \Akeneo\Pim\Structure\Component\Normalizer\ExternalApi\AssociationTypeNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.association_type']) ? $this->services['pim_catalog.normalizer.standard.association_type'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_AssociationTypeService.php')) && false ?: '_'});
