<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_localization.controller.locale' shared service.

return $this->services['pim_localization.controller.locale'] = new \Akeneo\Platform\Bundle\UIBundle\Controller\LocaleController(${($_ = isset($this->services['pim_localization.provider.ui_locale']) ? $this->services['pim_localization.provider.ui_locale'] : $this->load(__DIR__.'/getPimLocalization_Provider_UiLocaleService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_internal_api_serializer']) ? $this->services['pim_internal_api_serializer'] : $this->load(__DIR__.'/getPimInternalApiSerializerService.php')) && false ?: '_'});
