<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.form.type.acl_collection' shared service.

return $this->services['pim_user.form.type.acl_collection'] = new \Akeneo\UserManagement\Bundle\Form\Type\PrivilegeCollectionType();
