<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.index_product_models' shared service.

$a = ${($_ = isset($this->services['pim_catalog.elasticsearch.indexer.product_model']) ? $this->services['pim_catalog.elasticsearch.indexer.product_model'] : $this->load(__DIR__.'/getPimCatalog_Elasticsearch_Indexer_ProductModelService.php')) && false ?: '_'};

return $this->services['pim_catalog.event_subscriber.index_product_models'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\IndexProductModelsSubscriber($a, $a, $a);
