<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.standard.job_instance' shared service.

return $this->services['pim_connector.array_converter.standard.job_instance'] = new \Akeneo\Tool\Component\Connector\ArrayConverter\DummyConverter(${($_ = isset($this->services['pim_connector.array_convertor.checker.fields_requirement']) ? $this->services['pim_connector.array_convertor.checker.fields_requirement'] : $this->services['pim_connector.array_convertor.checker.fields_requirement'] = new \Akeneo\Tool\Component\Connector\ArrayConverter\FieldsRequirementChecker()) && false ?: '_'}, array(0 => 'code', 1 => 'type', 2 => 'connector', 3 => 'label', 4 => 'alias'), array(0 => 'code', 1 => 'type', 2 => 'connector', 3 => 'label'));
