<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.attributetype.file' shared service.

return $this->services['pim_catalog.attributetype.file'] = new \Akeneo\Pim\Structure\Component\AttributeType\FileType('media');
