<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.job.remove_from_category' shared service.

return $this->services['pim_enrich.job.remove_from_category'] = new \Akeneo\Tool\Component\Batch\Job\Job('remove_from_category', ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->getAkeneoBatch_JobRepositoryService()) && false ?: '_'}, array(0 => ${($_ = isset($this->services['pim_enrich.step.remove_from_category.mass_edit']) ? $this->services['pim_enrich.step.remove_from_category.mass_edit'] : $this->load(__DIR__.'/getPimEnrich_Step_RemoveFromCategory_MassEditService.php')) && false ?: '_'}));
