<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.normalizer.attribute' shared service.

return $this->services['pim_api.normalizer.attribute'] = new \Akeneo\Pim\Structure\Component\Normalizer\ExternalApi\AttributeNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.attribute']) ? $this->services['pim_catalog.normalizer.standard.attribute'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_AttributeService.php')) && false ?: '_'});
