<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_structure_version.provider.structure_version.attribute' shared service.

$this->services['pim_structure_version.provider.structure_version.attribute'] = $instance = new \Akeneo\Pim\Enrichment\Bundle\StructureVersion\Provider\StructureVersion(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});

$instance->addResource('Akeneo\\Pim\\Structure\\Component\\Model\\AttributeGroup');
$instance->addResource('Akeneo\\Channel\\Component\\Model\\Locale');

return $instance;
