<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.archiver.archivable_file_writer_archiver' shared service.

return $this->services['pim_connector.archiver.archivable_file_writer_archiver'] = new \Akeneo\Tool\Component\Connector\Archiver\ArchivableFileWriterArchiver(${($_ = isset($this->services['pim_connector.factory.zip_filesystem']) ? $this->services['pim_connector.factory.zip_filesystem'] : $this->services['pim_connector.factory.zip_filesystem'] = new \Akeneo\Tool\Component\Connector\Archiver\ZipFilesystemFactory()) && false ?: '_'}, ${($_ = isset($this->services['oneup_flysystem.archivist_filesystem']) ? $this->services['oneup_flysystem.archivist_filesystem'] : $this->load(__DIR__.'/getOneupFlysystem_ArchivistFilesystemService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job.job_registry']) ? $this->services['akeneo_batch.job.job_registry'] : $this->load(__DIR__.'/getAkeneoBatch_Job_JobRegistryService.php')) && false ?: '_'});
