<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.step.xlsx_product.import_associations' shared service.

return $this->services['pim_connector.step.xlsx_product.import_associations'] = new \Akeneo\Tool\Component\Batch\Step\ItemStep('import_associations', ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->getAkeneoBatch_JobRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.reader.file.xlsx_association']) ? $this->services['pim_connector.reader.file.xlsx_association'] : $this->load(__DIR__.'/getPimConnector_Reader_File_XlsxAssociationService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.processor.denormalization.product_association']) ? $this->services['pim_connector.processor.denormalization.product_association'] : $this->load(__DIR__.'/getPimConnector_Processor_Denormalization_ProductAssociationService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.writer.database.product_association']) ? $this->services['pim_connector.writer.database.product_association'] : $this->load(__DIR__.'/getPimConnector_Writer_Database_ProductAssociationService.php')) && false ?: '_'}, 1);
