<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.standard_to_flat.family_variant.field_splitter' shared service.

return $this->services['pim_connector.array_converter.standard_to_flat.family_variant.field_splitter'] = new \Akeneo\Pim\Structure\Component\ArrayConverter\StandardToFlat\FamilyVariant\FieldSplitter();
