<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.product_grid.query.list_available_columns' shared service.

return $this->services['pim_datagrid.product_grid.query.list_available_columns'] = new \Oro\Bundle\PimDataGridBundle\Query\Sql\ListProductGridAvailableColumns(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['oro_datagrid.configuration.provider.chain']) ? $this->services['oro_datagrid.configuration.provider.chain'] : $this->load(__DIR__.'/getOroDatagrid_Configuration_Provider_ChainService.php')) && false ?: '_'});
