<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.serializer.normalizer.flat.option' shared service.

return $this->services['pim_versioning.serializer.normalizer.flat.option'] = new \Akeneo\Pim\Structure\Component\Normalizer\Versioning\AttributeOptionNormalizer();
