<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.form.type.group' shared service.

return $this->services['pim_user.form.type.group'] = new \Akeneo\UserManagement\Bundle\Form\Type\GroupType();
