<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.processor.denormalization.locale' shared service.

return $this->services['pim_connector.processor.denormalization.locale'] = new \Akeneo\Tool\Component\Connector\Processor\Denormalization\Processor(${($_ = isset($this->services['pim_catalog.repository.locale']) ? $this->services['pim_catalog.repository.locale'] : $this->getPimCatalog_Repository_LocaleService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.factory.locale']) ? $this->services['pim_catalog.factory.locale'] : $this->services['pim_catalog.factory.locale'] = new \Akeneo\Tool\Component\StorageUtils\Factory\SimpleFactory('Akeneo\\Channel\\Component\\Model\\Locale')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.updater.locale']) ? $this->services['pim_catalog.updater.locale'] : $this->services['pim_catalog.updater.locale'] = new \Akeneo\Channel\Component\Updater\LocaleUpdater()) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'});
