<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.group_type' shared service.

return $this->services['pim_enrich.form.group_type'] = ${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}->createNamed('pim_enrich_grouptype_form', 'Akeneo\\Pim\\Structure\\Bundle\\Form\\Type\\GroupTypeType');
