<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.not_null_properties' shared service.

return $this->services['pim_catalog.validator.constraint.not_null_properties'] = new \Akeneo\Pim\Structure\Component\Validator\Constraints\NotNullPropertiesValidator(array(0 => 'pim_reference_data_multiselect', 1 => 'pim_reference_data_simpleselect', 2 => 'pim_assets_collection'));
