<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.reader.database.products_and_variant_products_of_product_models' shared service.

return $this->services['pim_enrich.reader.database.products_and_variant_products_of_product_models'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\MassEdit\FilteredProductAndProductModelReader(${($_ = isset($this->services['pim_catalog.query.product_and_product_model_query_builder_factory']) ? $this->services['pim_catalog.query.product_and_product_model_query_builder_factory'] : $this->load(__DIR__.'/getPimCatalog_Query_ProductAndProductModelQueryBuilderFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.channel']) ? $this->services['pim_catalog.repository.channel'] : $this->getPimCatalog_Repository_ChannelService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.converter.metric']) ? $this->services['pim_catalog.converter.metric'] : $this->load(__DIR__.'/getPimCatalog_Converter_MetricService.php')) && false ?: '_'}, true);
