<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.controller.rest.job_execution' shared service.

return $this->services['pim_enrich.controller.rest.job_execution'] = new \Akeneo\Platform\Bundle\ImportExportBundle\Controller\InternalApi\JobExecutionController(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.event_listener.archivist']) ? $this->services['pim_connector.event_listener.archivist'] : $this->load(__DIR__.'/getPimConnector_EventListener_ArchivistService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch_queue.manager.job_execution_manager']) ? $this->services['akeneo_batch_queue.manager.job_execution_manager'] : $this->load(__DIR__.'/getAkeneoBatchQueue_Manager_JobExecutionManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.repository.job_execution']) ? $this->services['pim_enrich.repository.job_execution'] : $this->load(__DIR__.'/getPimEnrich_Repository_JobExecutionService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_internal_api_serializer']) ? $this->services['pim_internal_api_serializer'] : $this->load(__DIR__.'/getPimInternalApiSerializerService.php')) && false ?: '_'});
