<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.controller.rest.sequential_edit' shared service.

return $this->services['pim_enrich.controller.rest.sequential_edit'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\SequentialEditController(${($_ = isset($this->services['oro_datagrid.mass_action.parameters_parser']) ? $this->services['oro_datagrid.mass_action.parameters_parser'] : $this->services['oro_datagrid.mass_action.parameters_parser'] = new \Oro\Bundle\DataGridBundle\Extension\MassAction\MassActionParametersParser()) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.adapter.oro_to_pim_grid_filter']) ? $this->services['pim_datagrid.adapter.oro_to_pim_grid_filter'] : $this->load(__DIR__.'/getPimDatagrid_Adapter_OroToPimGridFilterService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.query.product_and_product_model_query_sequential_edit_builder_factory']) ? $this->services['pim_enrich.query.product_and_product_model_query_sequential_edit_builder_factory'] : $this->load(__DIR__.'/getPimEnrich_Query_ProductAndProductModelQuerySequentialEditBuilderFactoryService.php')) && false ?: '_'});
