<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_notification.email.email_notifier' shared service.

return $this->services['pim_notification.email.email_notifier'] = new \Akeneo\Platform\Bundle\NotificationBundle\Email\MailNotifier(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, 'no-reply@example.com');
