<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.datasource.associated_product_model' shared service.

return $this->services['pim_datagrid.datasource.associated_product_model'] = new \Oro\Bundle\PimDataGridBundle\Datasource\AssociatedProductModelDatasource(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.query.product_and_product_model_query_builder_from_size_factory']) ? $this->services['pim_enrich.query.product_and_product_model_query_builder_from_size_factory'] : $this->load(__DIR__.'/getPimEnrich_Query_ProductAndProductModelQueryBuilderFromSizeFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid_serializer']) ? $this->services['pim_datagrid_serializer'] : $this->load(__DIR__.'/getPimDatagridSerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber']) ? $this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber'] : $this->services['pim_datagrid.event_subscriber.filter_entity_with_values_subscriber'] = new \Oro\Bundle\PimDataGridBundle\EventSubscriber\FilterEntityWithValuesSubscriber()) && false ?: '_'});
