<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.query.filter.product.field_dumper' shared service.

return $this->services['pim_catalog.query.filter.product.field_dumper'] = new \Akeneo\Pim\Enrichment\Bundle\Command\ProductQueryHelp\FieldFilterDumper(${($_ = isset($this->services['pim_catalog.query.filter.product_registry']) ? $this->services['pim_catalog.query.filter.product_registry'] : $this->getPimCatalog_Query_Filter_ProductRegistryService()) && false ?: '_'});
