<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.group' shared service.

return $this->services['pim_enrich.normalizer.group'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\GroupNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.group']) ? $this->services['pim_catalog.normalizer.standard.group'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_structure_version.provider.structure_version.group']) ? $this->services['pim_structure_version.provider.structure_version.group'] : $this->load(__DIR__.'/getPimStructureVersion_Provider_StructureVersion_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_versioning.manager.version']) ? $this->services['pim_versioning.manager.version'] : $this->load(__DIR__.'/getPimVersioning_Manager_VersionService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.normalizer.version']) ? $this->services['pim_enrich.normalizer.version'] : $this->load(__DIR__.'/getPimEnrich_Normalizer_VersionService.php')) && false ?: '_'});
