<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.security.acl.voter.overall_access' shared service.

return $this->services['pim_api.security.acl.voter.overall_access'] = new \Akeneo\Tool\Bundle\ApiBundle\Security\ActionAclVoter(${($_ = isset($this->services['security.acl.voter.basic_permissions']) ? $this->services['security.acl.voter.basic_permissions'] : $this->load(__DIR__.'/getSecurity_Acl_Voter_BasicPermissionsService.php')) && false ?: '_'}, 'pim_api_overall_access');
