<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.step.delete_products_and_product_models.mass_edit' shared service.

return $this->services['pim_enrich.step.delete_products_and_product_models.mass_edit'] = new \Akeneo\Tool\Component\Connector\Step\TaskletStep('delete_products_and_product_models', ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->getAkeneoBatch_JobRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['pim_enrich.tasklet.delete_products_and_product_models']) ? $this->services['pim_enrich.tasklet.delete_products_and_product_models'] : $this->load(__DIR__.'/getPimEnrich_Tasklet_DeleteProductsAndProductModelsService.php')) && false ?: '_'});
