<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.validator.constraints.filter_structure_attribute_validator' shared service.

return $this->services['pim_connector.validator.constraints.filter_structure_attribute_validator'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\FilterStructureAttributeValidator(${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->getPimCatalog_Repository_AttributeService()) && false ?: '_'});
