<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.provider.field.base' shared service.

return $this->services['pim_enrich.provider.field.base'] = new \Akeneo\Platform\Bundle\UIBundle\Provider\Field\BaseFieldProvider();
