<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.tasklet.delete_products_and_product_models' shared service.

return $this->services['pim_enrich.tasklet.delete_products_and_product_models'] = new \Akeneo\Pim\Enrichment\Component\Product\Job\DeleteProductsAndProductModelsTasklet(${($_ = isset($this->services['pim_catalog.query.product_and_product_model_query_builder_factory']) ? $this->services['pim_catalog.query.product_and_product_model_query_builder_factory'] : $this->load(__DIR__.'/getPimCatalog_Query_ProductAndProductModelQueryBuilderFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.remover.product']) ? $this->services['pim_catalog.remover.product'] : $this->load(__DIR__.'/getPimCatalog_Remover_ProductService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.remover.product_model']) ? $this->services['pim_catalog.remover.product_model'] : $this->load(__DIR__.'/getPimCatalog_Remover_ProductModelService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.doctrine.cache_clearer']) ? $this->services['pim_connector.doctrine.cache_clearer'] : $this->load(__DIR__.'/getPimConnector_Doctrine_CacheClearerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.filter.chained']) ? $this->services['pim_catalog.filter.chained'] : $this->load(__DIR__.'/getPimCatalog_Filter_ChainedService.php')) && false ?: '_'}, 100);
