<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.compute_family_variant_structure_changes' shared service.

return $this->services['pim_catalog.event_subscriber.compute_family_variant_structure_changes'] = new \Akeneo\Pim\Structure\Bundle\EventSubscriber\ComputeFamilyVariantStructureChangesSubscriber(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch_queue.launcher.queue_job_launcher']) ? $this->services['akeneo_batch_queue.launcher.queue_job_launcher'] : $this->load(__DIR__.'/getAkeneoBatchQueue_Launcher_QueueJobLauncherService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job.job_instance_repository']) ? $this->services['akeneo_batch.job.job_instance_repository'] : $this->getAkeneoBatch_Job_JobInstanceRepositoryService()) && false ?: '_'}, 'compute_family_variant_structure_changes');
