<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.security.login' shared service.

return $this->services['pim_user.security.login'] = new \Akeneo\UserManagement\Bundle\EventListener\LoginSubscriber(${($_ = isset($this->services['pim_user.manager']) ? $this->services['pim_user.manager'] : $this->load(__DIR__.'/getPimUser_ManagerService.php')) && false ?: '_'});
