<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.guesser.file_type' shared service.

return $this->services['pim_enrich.guesser.file_type'] = new \Akeneo\Pim\Enrichment\Bundle\File\FileTypeGuesser();
