<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrichment.provider.form.job_instance' shared service.

return $this->services['pim_enrichment.provider.form.job_instance'] = new \Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider(array('csv_category_export' => 'pim-job-instance-csv-base-export', 'csv_group_export' => 'pim-job-instance-csv-base-export', 'csv_product_export' => 'pim-job-instance-csv-product-export', 'csv_product_model_export' => 'pim-job-instance-csv-product-model-export', 'xlsx_category_export' => 'pim-job-instance-xlsx-base-export', 'xlsx_group_export' => 'pim-job-instance-xlsx-base-export', 'xlsx_product_export' => 'pim-job-instance-xlsx-product-export', 'xlsx_product_model_export' => 'pim-job-instance-xlsx-product-model-export', 'csv_category_import' => 'pim-job-instance-csv-base-import', 'csv_group_import' => 'pim-job-instance-csv-base-import', 'csv_product_import' => 'pim-job-instance-csv-product-import', 'csv_product_model_import' => 'pim-job-instance-csv-product-model-import', 'xlsx_category_import' => 'pim-job-instance-xlsx-base-import', 'xlsx_group_import' => 'pim-job-instance-xlsx-base-import', 'xlsx_product_import' => 'pim-job-instance-xlsx-product-import', 'xlsx_product_model_import' => 'pim-job-instance-xlsx-product-model-import'));
