<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.completeness.checker' shared service.

$a = ${($_ = isset($this->services['pim_catalog.repository.cached_attribute']) ? $this->services['pim_catalog.repository.cached_attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedAttributeService.php')) && false ?: '_'};

$this->services['pim_catalog.completeness.checker'] = $instance = new \Akeneo\Pim\Enrichment\Component\Product\Completeness\Checker\ValueCompleteChecker($a);

$instance->addProductValueChecker(new \Akeneo\Pim\Enrichment\Component\Product\Completeness\Checker\MediaCompleteChecker($a));
$instance->addProductValueChecker(new \Akeneo\Pim\Enrichment\Component\Product\Completeness\Checker\MetricCompleteChecker($a));
$instance->addProductValueChecker(new \Akeneo\Pim\Enrichment\Component\Product\Completeness\Checker\PriceCompleteChecker($a));
$instance->addProductValueChecker(new \Akeneo\Pim\Enrichment\Component\Product\Completeness\Checker\SimpleCompleteChecker());

return $instance;
