<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.setter.family_field' shared service.

return $this->services['pim_catalog.updater.setter.family_field'] = new \Akeneo\Pim\Enrichment\Component\Product\Updater\Setter\FamilyFieldSetter(${($_ = isset($this->services['pim_catalog.repository.cached_family']) ? $this->services['pim_catalog.repository.cached_family'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedFamilyService.php')) && false ?: '_'}, array(0 => 'family'));
