<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.event_subscriber.add_remove_version' shared service.

return $this->services['pim_versioning.event_subscriber.add_remove_version'] = new \Akeneo\Tool\Bundle\VersioningBundle\EventSubscriber\AddRemoveVersionSubscriber(${($_ = isset($this->services['pim_versioning.factory.version']) ? $this->services['pim_versioning.factory.version'] : $this->services['pim_versioning.factory.version'] = new \Akeneo\Tool\Bundle\VersioningBundle\Factory\VersionFactory('Akeneo\\Tool\\Component\\Versioning\\Model\\Version')) && false ?: '_'}, ${($_ = isset($this->services['pim_versioning.repository.version']) ? $this->services['pim_versioning.repository.version'] : $this->load(__DIR__.'/getPimVersioning_Repository_VersionService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'}, ${($_ = isset($this->services['pim_versioning.saver.version']) ? $this->services['pim_versioning.saver.version'] : $this->load(__DIR__.'/getPimVersioning_Saver_VersionService.php')) && false ?: '_'});
