<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.writer.file.family_variant.column_sorter' shared service.

return $this->services['pim_connector.writer.file.family_variant.column_sorter'] = new \Akeneo\Tool\Component\Connector\Writer\File\DefaultColumnSorter(${($_ = isset($this->services['pim_connector.array_converter.standard_to_flat.family_variant.field_splitter']) ? $this->services['pim_connector.array_converter.standard_to_flat.family_variant.field_splitter'] : $this->services['pim_connector.array_converter.standard_to_flat.family_variant.field_splitter'] = new \Akeneo\Pim\Structure\Component\ArrayConverter\StandardToFlat\FamilyVariant\FieldSplitter()) && false ?: '_'}, array(0 => 'code', 1 => 'family', 2 => 'label', 3 => 'variant-axes', 4 => 'variant-attributes'));
