<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.normalizer.image' shared service.

return $this->services['pim_enrich.normalizer.image'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\ImageNormalizer(${($_ = isset($this->services['pim_enrich.normalizer.file']) ? $this->services['pim_enrich.normalizer.file'] : $this->services['pim_enrich.normalizer.file'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\FileNormalizer()) && false ?: '_'});
