<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_volume_monitoring.event_listener.install_database' shared service.

return $this->services['pim_volume_monitoring.event_listener.install_database'] = new \Akeneo\Platform\Bundle\CatalogVolumeMonitoringBundle\EventListener\InstallDatabase(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
