<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.extension.mass_action.handler.export' shared service.

return $this->services['pim_datagrid.extension.mass_action.handler.export'] = new \Oro\Bundle\PimDataGridBundle\Extension\MassAction\Handler\ExportMassActionHandler(${($_ = isset($this->services['pim_datagrid.datasource.result_record.hydrator.object']) ? $this->services['pim_datagrid.datasource.result_record.hydrator.object'] : $this->services['pim_datagrid.datasource.result_record.hydrator.object'] = new \Oro\Bundle\PimDataGridBundle\Datasource\ResultRecord\Orm\ObjectHydrator()) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
