<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_reference_data.enrich.provider.empty_value.reference_data' shared service.

return $this->services['pim_reference_data.enrich.provider.empty_value.reference_data'] = new \Akeneo\Platform\Bundle\UIBundle\Provider\EmptyValue\ReferenceDataEmptyValueProvider();
