<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.validator.constraints.value_should_not_contains_blacklisted_characters' shared service.

return $this->services['pim_user.validator.constraints.value_should_not_contains_blacklisted_characters'] = new \Akeneo\UserManagement\Bundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharactersValidator();
