<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.type.export_select_family' shared service.

return $this->services['pim_enrich.form.type.export_select_family'] = new \Akeneo\Pim\Structure\Bundle\Form\Type\SelectFamilyType(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
