<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.standard_to_flat.attribute_group' shared service.

return $this->services['pim_connector.array_converter.standard_to_flat.attribute_group'] = new \Akeneo\Pim\Structure\Component\ArrayConverter\StandardToFlat\AttributeGroup();
