<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.serializer.normalizer.flat.group' shared service.

return $this->services['pim_versioning.serializer.normalizer.flat.group'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Versioning\GroupNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.group']) ? $this->services['pim_catalog.normalizer.standard.group'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_GroupService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_versioning.serializer.normalizer.flat.label_translation']) ? $this->services['pim_versioning.serializer.normalizer.flat.label_translation'] : $this->services['pim_versioning.serializer.normalizer.flat.label_translation'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Versioning\TranslationNormalizer()) && false ?: '_'});
