<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.normalizer.standard.job_instance' shared service.

return $this->services['pim_catalog.normalizer.standard.job_instance'] = new \Akeneo\Tool\Component\Batch\Normalizer\Standard\JobInstanceNormalizer();
