<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'akeneo_batch.logger.batch_log_handler' shared service.

return $this->services['akeneo_batch.logger.batch_log_handler'] = new \Akeneo\Tool\Bundle\BatchBundle\Monolog\Handler\BatchLogHandler(100, true, NULL, false, ($this->targetDirs[2].'/logs/batch'));
