<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_datagrid.provider.resolver' shared service.

return $this->services['oro_datagrid.provider.resolver'] = new \Oro\Bundle\DataGridBundle\Provider\SystemAwareResolver($this);
