<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_filter.boolean_filter' shared service.

return $this->services['oro_filter.boolean_filter'] = new \Oro\Bundle\FilterBundle\Filter\BooleanFilter(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['oro_filter.filter_utility']) ? $this->services['oro_filter.filter_utility'] : $this->services['oro_filter.filter_utility'] = new \Oro\Bundle\FilterBundle\Filter\FilterUtility()) && false ?: '_'});
