<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_security.acl.manager' shared service.

return $this->services['oro_security.acl.manager'] = new \Oro\Bundle\SecurityBundle\Acl\Persistence\AclManager(${($_ = isset($this->services['oro_security.acl.object_identity_factory']) ? $this->services['oro_security.acl.object_identity_factory'] : $this->getOroSecurity_Acl_ObjectIdentityFactoryService()) && false ?: '_'}, ${($_ = isset($this->services['oro_security.acl.extension_selector']) ? $this->services['oro_security.acl.extension_selector'] : $this->getOroSecurity_Acl_ExtensionSelectorService()) && false ?: '_'}, ${($_ = isset($this->services['security.acl.provider']) ? $this->services['security.acl.provider'] : $this->load(__DIR__.'/getSecurity_Acl_ProviderService.php')) && false ?: '_'}, new \Oro\Bundle\SecurityBundle\Acl\Persistence\AceManipulationHelper(), 'Oro\\Bundle\\SecurityBundle\\Acl\\Persistence\\AclPrivilegeRepository');
