<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oneup_flysystem.tmp_storage_filesystem' shared service.

$this->services['oneup_flysystem.tmp_storage_filesystem'] = $instance = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local('/tmp/pim/file_storage', 2, 2, array('file' => array('public' => 420, 'private' => 384), 'dir' => array('public' => 493, 'private' => 448))), array('disable_asserts' => false));

$instance->addPlugin(${($_ = isset($this->services['oneup_flysystem.plugin.list_files']) ? $this->services['oneup_flysystem.plugin.list_files'] : $this->services['oneup_flysystem.plugin.list_files'] = new \League\Flysystem\Plugin\ListFiles()) && false ?: '_'});

return $instance;
