<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_filter.form.type.filter.datetime_range' shared service.

return $this->services['oro_filter.form.type.filter.datetime_range'] = new \Oro\Bundle\FilterBundle\Form\Type\Filter\DateTimeRangeFilterType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
