<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oro_datagrid.mass_action.dispatcher' shared service.

return $this->services['oro_datagrid.mass_action.dispatcher'] = new \Oro\Bundle\DataGridBundle\Extension\MassAction\MassActionDispatcher($this, ${($_ = isset($this->services['oro_datagrid.datagrid.manager']) ? $this->services['oro_datagrid.datagrid.manager'] : $this->services['oro_datagrid.datagrid.manager'] = new \Oro\Bundle\DataGridBundle\Datagrid\Manager($this)) && false ?: '_'}, ${($_ = isset($this->services['oro_datagrid.datagrid.request_params']) ? $this->services['oro_datagrid.datagrid.request_params'] : $this->getOroDatagrid_Datagrid_RequestParamsService()) && false ?: '_'});
