<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.controller.rest.product_model_category' shared service.

return $this->services['pim_enrich.controller.rest.product_model_category'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ProductModelCategoryController(${($_ = isset($this->services['pim_catalog.repository.product_model']) ? $this->services['pim_catalog.repository.product_model'] : $this->getPimCatalog_Repository_ProductModelService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.product_model_category']) ? $this->services['pim_catalog.repository.product_model_category'] : $this->load(__DIR__.'/getPimCatalog_Repository_ProductModelCategoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.filter.chained']) ? $this->services['pim_catalog.filter.chained'] : $this->load(__DIR__.'/getPimCatalog_Filter_ChainedService.php')) && false ?: '_'});
