<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.normalizer.product.product_values' shared service.

return $this->services['pim_datagrid.normalizer.product.product_values'] = new \Oro\Bundle\PimDataGridBundle\Normalizer\Product\ProductValuesNormalizer(${($_ = isset($this->services['pim_catalog.localization.presenter.registry']) ? $this->services['pim_catalog.localization.presenter.registry'] : $this->load(__DIR__.'/getPimCatalog_Localization_Presenter_RegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_user.context.user']) ? $this->services['pim_user.context.user'] : $this->getPimUser_Context_UserService()) && false ?: '_'});
