<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.adder.group_field' shared service.

return $this->services['pim_catalog.updater.adder.group_field'] = new \Akeneo\Pim\Enrichment\Component\Product\Updater\Adder\GroupFieldAdder(${($_ = isset($this->services['pim_catalog.repository.group']) ? $this->services['pim_catalog.repository.group'] : $this->getPimCatalog_Repository_GroupService()) && false ?: '_'}, array(0 => 'groups'));
