<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.controller.datagrid' shared service.

return $this->services['pim_datagrid.controller.datagrid'] = new \Oro\Bundle\PimDataGridBundle\Controller\DatagridController(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->getTemplatingService()) && false ?: '_'}, ${($_ = isset($this->services['oro_datagrid.datagrid.metadata_parser']) ? $this->services['oro_datagrid.datagrid.metadata_parser'] : $this->getOroDatagrid_Datagrid_MetadataParserService()) && false ?: '_'});
