<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor' shared service.

return $this->services['pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\ArrayConverter\FlatToStandard\AttributeColumnInfoExtractor(${($_ = isset($this->services['pim_catalog.repository.cached_attribute']) ? $this->services['pim_catalog.repository.cached_attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedAttributeService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.cached_channel']) ? $this->services['pim_catalog.repository.cached_channel'] : $this->getPimCatalog_Repository_CachedChannelService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.cached_locale']) ? $this->services['pim_catalog.repository.cached_locale'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedLocaleService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.array_converter.flat_to_standard.product.association_columns_resolver']) ? $this->services['pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'] : $this->load(__DIR__.'/getPimConnector_ArrayConverter_FlatToStandard_Product_AssociationColumnsResolverService.php')) && false ?: '_'});
