<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.extension.formatter.property.datetime_property' shared service.

return $this->services['pim_datagrid.extension.formatter.property.datetime_property'] = new \Oro\Bundle\PimDataGridBundle\Extension\Formatter\Property\DateTimeProperty(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.presenter.datetime']) ? $this->services['pim_catalog.localization.presenter.datetime'] : $this->getPimCatalog_Localization_Presenter_DatetimeService()) && false ?: '_'});
