<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_import_export.factory.job_notification' shared service.

return $this->services['pim_import_export.factory.job_notification'] = new \Akeneo\Platform\Bundle\ImportExportBundle\Factory\NotificationFactory(array(0 => 'import', 1 => 'export'), 'Akeneo\\Platform\\Bundle\\NotificationBundle\\Entity\\Notification');
