<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.writer.database.job_instance' shared service.

return $this->services['pim_connector.writer.database.job_instance'] = new \Akeneo\Tool\Component\Connector\Writer\Database\JobInstanceWriter(${($_ = isset($this->services['akeneo_batch.saver.job_instance']) ? $this->services['akeneo_batch.saver.job_instance'] : $this->load(__DIR__.'/getAkeneoBatch_Saver_JobInstanceService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'});
