<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.event_listener.add_username_to_grid_listener' shared service.

return $this->services['pim_enrich.event_listener.add_username_to_grid_listener'] = new \Oro\Bundle\PimDataGridBundle\EventListener\AddUsernameToGridListener(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'});
