<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_analytics.data_collector.version' shared service.

return $this->services['pim_analytics.data_collector.version'] = new \Akeneo\Platform\Bundle\AnalyticsBundle\DataCollector\VersionDataCollector(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.version_provider']) ? $this->services['pim_catalog.version_provider'] : $this->services['pim_catalog.version_provider'] = new \Akeneo\Platform\VersionProvider('Akeneo\\Platform\\CommunityVersion')) && false ?: '_'}, ${($_ = isset($this->services['pim_installer.install_status_manager']) ? $this->services['pim_installer.install_status_manager'] : $this->load(__DIR__.'/getPimInstaller_InstallStatusManagerService.php')) && false ?: '_'}, 'dev');
