<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.controller.user_group_rest' shared service.

return $this->services['pim_user.controller.user_group_rest'] = new \Akeneo\UserManagement\Bundle\Controller\Rest\UserGroupController(${($_ = isset($this->services['pim_user.repository.group']) ? $this->services['pim_user.repository.group'] : $this->load(__DIR__.'/getPimUser_Repository_GroupService.php')) && false ?: '_'});
