<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.writer.file.yaml' shared service.

return $this->services['pim_connector.writer.file.yaml'] = new \Akeneo\Tool\Component\Connector\Writer\File\Yaml\Writer(${($_ = isset($this->services['pim_connector.array_converter.dummy']) ? $this->services['pim_connector.array_converter.dummy'] : $this->load(__DIR__.'/getPimConnector_ArrayConverter_DummyService.php')) && false ?: '_'});
