<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.family_variant.add_unique_attributes' shared service.

return $this->services['pim_catalog.family_variant.add_unique_attributes'] = new \Akeneo\Pim\Structure\Component\FamilyVariant\AddUniqueAttributes();
