<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.form.type.category' shared service.

return $this->services['pim_enrich.form.type.category'] = new \Akeneo\Pim\Enrichment\Bundle\Form\Type\CategoryType('Akeneo\\Pim\\Enrichment\\Component\\Category\\Model\\Category', 'Akeneo\\Pim\\Enrichment\\Component\\Category\\Model\\CategoryTranslation');
