<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_analytics.controller.data' shared service.

return $this->services['pim_analytics.controller.data'] = new \Akeneo\Platform\Bundle\AnalyticsBundle\Controller\DataController(${($_ = isset($this->services['pim_analytics.data_collector.chained']) ? $this->services['pim_analytics.data_collector.chained'] : $this->load(__DIR__.'/getPimAnalytics_DataCollector_ChainedService.php')) && false ?: '_'});
