<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.adder.registry' shared service.

$this->services['pim_catalog.updater.adder.registry'] = $instance = new \Akeneo\Pim\Enrichment\Component\Product\Updater\Adder\AdderRegistry(${($_ = isset($this->services['pim_catalog.repository.cached_attribute']) ? $this->services['pim_catalog.repository.cached_attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedAttributeService.php')) && false ?: '_'});

$instance->register(${($_ = isset($this->services['pim_catalog.updater.adder.category_field']) ? $this->services['pim_catalog.updater.adder.category_field'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_CategoryFieldService.php')) && false ?: '_'});
$instance->register(${($_ = isset($this->services['pim_catalog.updater.adder.group_field']) ? $this->services['pim_catalog.updater.adder.group_field'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_GroupFieldService.php')) && false ?: '_'});
$instance->register(${($_ = isset($this->services['pim_catalog.updater.adder.multiselect_value']) ? $this->services['pim_catalog.updater.adder.multiselect_value'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_MultiselectValueService.php')) && false ?: '_'});
$instance->register(${($_ = isset($this->services['pim_catalog.updater.adder.association_field']) ? $this->services['pim_catalog.updater.adder.association_field'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_AssociationFieldService.php')) && false ?: '_'});
$instance->register(${($_ = isset($this->services['pim_catalog.updater.adder.price_collection_value']) ? $this->services['pim_catalog.updater.adder.price_collection_value'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_PriceCollectionValueService.php')) && false ?: '_'});

return $instance;
