<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_comment.controller.comment' shared service.

return $this->services['pim_comment.controller.comment'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\CommentController(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['pim_comment.remover.comment']) ? $this->services['pim_comment.remover.comment'] : $this->load(__DIR__.'/getPimComment_Remover_CommentService.php')) && false ?: '_'}, 'Akeneo\\Pim\\Enrichment\\Component\\Comment\\Model\\Comment');
