<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.serializer.normalizer.flat.metric' shared service.

return $this->services['pim_versioning.serializer.normalizer.flat.metric'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Versioning\Product\MetricNormalizer();
