<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_installer.directories_registry' shared service.

return $this->services['pim_installer.directories_registry'] = new \Akeneo\Platform\Bundle\InstallerBundle\PimDirectoriesRegistry(array(0 => ($this->targetDirs[3].'/app/file_storage/catalog'), 1 => '/tmp/pim/file_storage', 2 => ($this->targetDirs[3].'/app/archive'), 3 => ($this->targetDirs[3].'/app/uploads/product'), 4 => ($this->targetDirs[2].'/logs'), 5 => '/tmp/pim/upload_tmp_dir'));
