<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.currency_disabling' shared service.

return $this->services['pim_catalog.event_subscriber.currency_disabling'] = new \Akeneo\Channel\Bundle\EventListener\CurrencyDisablingSubscriber(${($_ = isset($this->services['pim_catalog.repository.channel']) ? $this->services['pim_catalog.repository.channel'] : $this->getPimCatalog_Repository_ChannelService()) && false ?: '_'});
