<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_reference_data.controller.configuration_rest' shared service.

return $this->services['pim_reference_data.controller.configuration_rest'] = new \Akeneo\Pim\Structure\Bundle\Controller\InternalApi\ReferenceDataConfigurationRestController(${($_ = isset($this->services['pim_reference_data.registry']) ? $this->services['pim_reference_data.registry'] : $this->services['pim_reference_data.registry'] = new \Akeneo\Pim\Structure\Component\ReferenceData\ConfigurationRegistry()) && false ?: '_'}, ${($_ = isset($this->services['pim_internal_api_serializer']) ? $this->services['pim_internal_api_serializer'] : $this->load(__DIR__.'/getPimInternalApiSerializerService.php')) && false ?: '_'});
