<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.processor.denormalization.job_instance' shared service.

$a = ${($_ = isset($this->services['akeneo_batch.updater.job_instance']) ? $this->services['akeneo_batch.updater.job_instance'] : $this->load(__DIR__.'/getAkeneoBatch_Updater_JobInstanceService.php')) && false ?: '_'};
$b = ${($_ = isset($this->services['akeneo_batch.job.job_registry']) ? $this->services['akeneo_batch.job.job_registry'] : $this->load(__DIR__.'/getAkeneoBatch_Job_JobRegistryService.php')) && false ?: '_'};

if (isset($this->services['pim_connector.processor.denormalization.job_instance'])) {
    return $this->services['pim_connector.processor.denormalization.job_instance'];
}

return $this->services['pim_connector.processor.denormalization.job_instance'] = new \Akeneo\Tool\Component\Connector\Processor\Denormalization\JobInstanceProcessor(${($_ = isset($this->services['akeneo_batch.job.job_instance_repository']) ? $this->services['akeneo_batch.job.job_instance_repository'] : $this->getAkeneoBatch_Job_JobInstanceRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.factory.job_instance']) ? $this->services['pim_connector.factory.job_instance'] : $this->services['pim_connector.factory.job_instance'] = new \Akeneo\Tool\Component\StorageUtils\Factory\SimpleFactory('Akeneo\\Tool\\Component\\Batch\\Model\\JobInstance')) && false ?: '_'}, $a, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job.job_parameters_validator']) ? $this->services['akeneo_batch.job.job_parameters_validator'] : $this->load(__DIR__.'/getAkeneoBatch_Job_JobParametersValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_parameters_factory']) ? $this->services['akeneo_batch.job_parameters_factory'] : $this->load(__DIR__.'/getAkeneoBatch_JobParametersFactoryService.php')) && false ?: '_'}, $b);
