<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.localizer.date' shared service.

return $this->services['pim_catalog.localization.localizer.date'] = new \Akeneo\Tool\Component\Localization\Localizer\DateLocalizer(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.factory.date']) ? $this->services['pim_catalog.localization.factory.date'] : $this->getPimCatalog_Localization_Factory_DateService()) && false ?: '_'}, array(0 => 'pim_catalog_date'));
