<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.step.xlsx_attribute_group_import.ensure_attribute_group_order' shared service.

return $this->services['pim_connector.step.xlsx_attribute_group_import.ensure_attribute_group_order'] = new \Akeneo\Tool\Component\Connector\Step\TaskletStep('ensure_attribute_group_order', ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_batch.job_repository']) ? $this->services['akeneo_batch.job_repository'] : $this->getAkeneoBatch_JobRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['pim_connector.tasklet.xlsx_attribute_group_import.ensure_attribute_group_order']) ? $this->services['pim_connector.tasklet.xlsx_attribute_group_import.ensure_attribute_group_order'] : $this->load(__DIR__.'/getPimConnector_Tasklet_XlsxAttributeGroupImport_EnsureAttributeGroupOrderService.php')) && false ?: '_'});
