<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.factory.product_and_product_model_cursor' shared service.

return $this->services['pim_catalog.factory.product_and_product_model_cursor'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\CursorFactory(${($_ = isset($this->services['akeneo_elasticsearch.client.product_and_product_model']) ? $this->services['akeneo_elasticsearch.client.product_and_product_model'] : $this->load(__DIR__.'/getAkeneoElasticsearch_Client_ProductAndProductModelService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.product']) ? $this->services['pim_catalog.repository.product'] : $this->getPimCatalog_Repository_ProductService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.product_model']) ? $this->services['pim_catalog.repository.product_model'] : $this->getPimCatalog_Repository_ProductModelService()) && false ?: '_'}, 100, 'pim_catalog_product');
