<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.processor.normalization.association_type' shared service.

return $this->services['pim_connector.processor.normalization.association_type'] = new \Akeneo\Tool\Component\Connector\Processor\Normalization\Processor(${($_ = isset($this->services['pim_catalog.normalizer.standard.association_type']) ? $this->services['pim_catalog.normalizer.standard.association_type'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_AssociationTypeService.php')) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'});
