<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.processor.denormalization.family' shared service.

return $this->services['pim_connector.processor.denormalization.family'] = new \Akeneo\Tool\Component\Connector\Processor\Denormalization\Processor(${($_ = isset($this->services['pim_catalog.repository.family']) ? $this->services['pim_catalog.repository.family'] : $this->getPimCatalog_Repository_FamilyService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.factory.family']) ? $this->services['pim_catalog.factory.family'] : $this->load(__DIR__.'/getPimCatalog_Factory_FamilyService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.updater.family']) ? $this->services['pim_catalog.updater.family'] : $this->load(__DIR__.'/getPimCatalog_Updater_FamilyService.php')) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['akeneo_storage_utils.doctrine.object_detacher']) ? $this->services['akeneo_storage_utils.doctrine.object_detacher'] : $this->load(__DIR__.'/getAkeneoStorageUtils_Doctrine_ObjectDetacherService.php')) && false ?: '_'});
