<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.validator.item.charset_validator' shared service.

return $this->services['pim_connector.validator.item.charset_validator'] = new \Akeneo\Tool\Component\Connector\Item\CharsetValidator();
