<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.updater.property_adder' shared service.

return $this->services['pim_catalog.updater.property_adder'] = new \Akeneo\Pim\Enrichment\Component\Product\Updater\PropertyAdder(${($_ = isset($this->services['pim_catalog.repository.cached_attribute']) ? $this->services['pim_catalog.repository.cached_attribute'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedAttributeService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.updater.adder.registry']) ? $this->services['pim_catalog.updater.adder.registry'] : $this->load(__DIR__.'/getPimCatalog_Updater_Adder_RegistryService.php')) && false ?: '_'});
