<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrich.controller.rest.versioning' shared service.

return $this->services['pim_enrich.controller.rest.versioning'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\VersioningController(${($_ = isset($this->services['pim_versioning.repository.version']) ? $this->services['pim_versioning.repository.version'] : $this->load(__DIR__.'/getPimVersioning_Repository_VersionService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.resolver.fqcn']) ? $this->services['pim_catalog.resolver.fqcn'] : $this->services['pim_catalog.resolver.fqcn'] = new \Akeneo\Pim\Enrichment\Bundle\Resolver\FQCNResolver($this)) && false ?: '_'}, ${($_ = isset($this->services['pim_internal_api_serializer']) ? $this->services['pim_internal_api_serializer'] : $this->load(__DIR__.'/getPimInternalApiSerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['pim_user.context.user']) ? $this->services['pim_user.context.user'] : $this->getPimUser_Context_UserService()) && false ?: '_'});
