<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_enrichment.updater.translatable' shared service.

return $this->services['pim_enrichment.updater.translatable'] = new \Akeneo\Tool\Component\Localization\TranslatableUpdater();
