<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.activated_locale' shared service.

return $this->services['pim_catalog.validator.constraint.activated_locale'] = new \Akeneo\Channel\Component\Validator\Constraint\ActivatedLocaleValidator(${($_ = isset($this->services['pim_catalog.repository.cached_locale']) ? $this->services['pim_catalog.repository.cached_locale'] : $this->load(__DIR__.'/getPimCatalog_Repository_CachedLocaleService.php')) && false ?: '_'});
