<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver' shared service.

return $this->services['pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'] = new \Akeneo\Pim\Enrichment\Component\Product\Connector\ArrayConverter\FlatToStandard\AttributeColumnsResolver(${($_ = isset($this->services['pim_catalog.repository.attribute']) ? $this->services['pim_catalog.repository.attribute'] : $this->getPimCatalog_Repository_AttributeService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.repository.currency']) ? $this->services['pim_catalog.repository.currency'] : $this->getPimCatalog_Repository_CurrencyService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.resolver.attribute_values']) ? $this->services['pim_catalog.resolver.attribute_values'] : $this->load(__DIR__.'/getPimCatalog_Resolver_AttributeValuesService.php')) && false ?: '_'});
