<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_user.form.reset' shared service.

return $this->services['pim_user.form.reset'] = ${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}->createNamed('pim_user_reset_form', 'Akeneo\\UserManagement\\Bundle\\Form\\Type\\ResetType', NULL, array('validation_groups' => array(0 => 'ResetPassword', 1 => 'Default')));
