<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.pagination.search_after_hal_paginator' shared service.

return $this->services['pim_api.pagination.search_after_hal_paginator'] = new \Akeneo\Tool\Component\Api\Pagination\SearchAfterHalPaginator(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
