<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.normalizer.channel' shared service.

return $this->services['pim_api.normalizer.channel'] = new \Akeneo\Channel\Component\Normalizer\ExternalApi\ChannelNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.channel']) ? $this->services['pim_catalog.normalizer.standard.channel'] : $this->load(__DIR__.'/getPimCatalog_Normalizer_Standard_ChannelService.php')) && false ?: '_'});
