<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.validator.constraint.file_allowed_extensions' shared service.

return $this->services['pim_catalog.validator.constraint.file_allowed_extensions'] = new \Akeneo\Pim\Structure\Component\Validator\Constraints\AllowedExtensionsValidator($this->parameters['pim_catalog_file_allowed_extensions']);
