<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_datagrid.extension.formatter.property.product_value.date_property' shared service.

return $this->services['pim_datagrid.extension.formatter.property.product_value.date_property'] = new \Oro\Bundle\PimDataGridBundle\Extension\Formatter\Property\ProductValue\DateProperty(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['pim_catalog.localization.presenter.date']) ? $this->services['pim_catalog.localization.presenter.date'] : $this->getPimCatalog_Localization_Presenter_DateService()) && false ?: '_'});
