<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.updater.family_variant' shared service.

return $this->services['pim_api.updater.family_variant'] = new \Akeneo\Pim\Structure\Component\Updater\ExternalApi\FamilyVariantUpdater(${($_ = isset($this->services['pim_catalog.updater.family_variant']) ? $this->services['pim_catalog.updater.family_variant'] : $this->load(__DIR__.'/getPimCatalog_Updater_FamilyVariantService.php')) && false ?: '_'});
