<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.localization.factory.currency' shared service.

return $this->services['pim_catalog.localization.factory.currency'] = new \Akeneo\Tool\Component\Localization\Factory\NumberFactory($this->parameters['pim_catalog.localization.factory.currency.formats']);
