<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_api.normalizer.file' shared service.

return $this->services['pim_api.normalizer.file'] = new \Akeneo\Tool\Component\Api\Normalizer\FileNormalizer(${($_ = isset($this->services['pim_catalog.normalizer.standard.file']) ? $this->services['pim_catalog.normalizer.standard.file'] : $this->services['pim_catalog.normalizer.standard.file'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\FileNormalizer()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
