<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_catalog.event_subscriber.add_unique_attributes_to_variant_product_attribute_set' shared service.

return $this->services['pim_catalog.event_subscriber.add_unique_attributes_to_variant_product_attribute_set'] = new \Akeneo\Pim\Structure\Bundle\EventSubscriber\AddUniqueAttributesToVariantProductAttributeSetSubscriber(${($_ = isset($this->services['pim_catalog.family_variant.add_unique_attributes']) ? $this->services['pim_catalog.family_variant.add_unique_attributes'] : $this->services['pim_catalog.family_variant.add_unique_attributes'] = new \Akeneo\Pim\Structure\Component\FamilyVariant\AddUniqueAttributes()) && false ?: '_'});
