<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_import_export.event_listener.inject_job_type' shared service.

return $this->services['pim_import_export.event_listener.inject_job_type'] = new \Oro\Bundle\PimDataGridBundle\EventListener\AddParametersToGridListener(array(0 => 'jobType'), ${($_ = isset($this->services['oro_datagrid.datagrid.request_params']) ? $this->services['oro_datagrid.datagrid.request_params'] : $this->getOroDatagrid_Datagrid_RequestParamsService()) && false ?: '_'});
