<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pim_versioning.factory.version_cursor' shared service.

return $this->services['pim_versioning.factory.version_cursor'] = new \Akeneo\Tool\Bundle\StorageUtilsBundle\Doctrine\ORM\Cursor\CursorFactory('Akeneo\\Tool\\Bundle\\StorageUtilsBundle\\Doctrine\\ORM\\Cursor\\Cursor', ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, 1000);
