<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.j3fdwqb' shared service.

return $this->services['security.request_matcher.j3fdwqb'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/rest/v1$');
