<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNzzgjun\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNzzgjun/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNzzgjun.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNzzgjun\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNzzgjun\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nzzgjun',
    'container.build_id' => '09000e91',
    'container.build_time' => 1549288252,
));
